import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';import{SUPABASE_URL,SUPABASE_ANON_KEY,FILE_BUCKET}from'./config.js?v=4.3.1';import{enqueue,flushQueue,allQueued}from'./offline.js?v=4.5.1';import{createOperations}from'./operations.js?v=4.5.1';
const sb=createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));let session,userId=null,org,plant,role,profile={},view='dashboard',records=[],channel,formHandler,viewHistory=[],handlingPop=false,lastHomeBack=0,onlineUsers=1,realtimeTimer;
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(x.t);x.t=setTimeout(()=>x.classList.remove('show'),2500)}
function setSync(){const x=$('#sync'),online=navigator.onLine;x.textContent=online?`● Online${onlineUsers>1?` • ${onlineUsers}`:''}`:'● Offline';x.title=online?`${onlineUsers} active PlantMaster user${onlineUsers===1?'':'s'} in this plant`:'Changes will queue until connection returns';x.style.color=online?'#32d39a':'#fbbf24'}
const operations=createOperations({sb,$,esc,toast,state:()=>({session,userId,org,plant,role,profile,email:session?.user?.email||''})});
function ensureCoreToolbar(){
  const bar=$('#toolbar');
  if(!bar)return;
  if(!$('#search')||!$('#add'))bar.innerHTML='<input id="search" placeholder="Search current module…"><button id="add">＋ Add</button>';
  $('#search').oninput=()=>view==='dashboard'?globalSearch($('#search').value):renderList();
  $('#add').onclick=dispatchAdd;
}
function dispatchAdd(){
  if(['assets','work','files'].includes(view))return openRecordForm();
  if(view==='support')return openSupportForm();
  if(view==='solver')return phase3Form('problem_cases',[['title','Problem title'],['symptoms','Symptoms'],['alarm_code','Alarm code']]);
  if(view==='manuals')return createManualInput();
  if(view==='checklists')return phase2Form('checklist_templates',[['name','Checklist name'],['schedule','Schedule'],['shift_name','Shift'],['instructions','Instructions']]);
  if(view==='maintenance')return phase2Form('maintenance_plans',[['title','Title'],['frequency','Frequency'],['priority','Priority'],['next_due','Due date','date'],['description','Description']]);
  if(view==='inventory')return inventoryChoice();
}

async function init(){setSync();const{data}=await sb.auth.getSession();session=data.session;$('#boot').hidden=true;if(!session)return showAuth();await loadWorkspace()}
function showAuth(){$('#auth').hidden=false;$('#app').hidden=true}
function authCredentials(){const email=$('#email').value.trim(),password=$('#password').value;if(!email){$('#authMsg').textContent='Enter your work email first.';$('#email').focus();return null}if(!/^\S+@\S+\.\S+$/.test(email)){ $('#authMsg').textContent='Enter a valid email address.';return null}if(password.length<8){$('#authMsg').textContent='Password must contain at least 8 characters.';$('#password').focus();return null}return{email,password}}
$('#authForm').onsubmit=async e=>{e.preventDefault();const credentials=authCredentials();if(!credentials)return;$('#authMsg').textContent='Signing in…';const{error}=await sb.auth.signInWithPassword(credentials);$('#authMsg').textContent=error?.message||''};
$('#signUp').onclick=async()=>{const credentials=authCredentials();if(!credentials)return;$('#authMsg').textContent='Creating account…';const{data:result,error}=await sb.auth.signUp({email:credentials.email,password:credentials.password,options:{emailRedirectTo:location.origin+location.pathname}});if(error){$('#authMsg').textContent=error.message;return}$('#authMsg').textContent=result.session?'Account created and signed in.':'Account created. Check your email confirmation link, then return and sign in.'};
sb.auth.onAuthStateChange(async(_,s)=>{session=s;if(s)await loadWorkspace();else showAuth()});
async function loadWorkspace(){let authUser=session?.user;if(!authUser){const result=await sb.auth.getUser();authUser=result.data.user;}const uid=authUser?.id;if(!uid){showAuth();return}userId=uid;await sb.from('profiles').upsert({id:uid,full_name:authUser.user_metadata?.full_name||authUser.email||''},{onConflict:'id',ignoreDuplicates:true});const inviteToken=new URLSearchParams(location.search).get('invite');if(inviteToken){const accepted=await sb.rpc('accept_invitation',{invite_token:inviteToken});if(accepted.error)toast(accepted.error.message);else{toast('Invitation accepted — workspace joined');const clean=new URL(location.href);clean.searchParams.delete('invite');history.replaceState({},'',clean.pathname+clean.search+clean.hash)}}const{data:profileRow}=await sb.from('profiles').select('*').eq('id',uid).maybeSingle();profile=profileRow||{id:uid,full_name:authUser.email||''};const{data:m,error}=await sb.from('organization_members').select('organization_id,role,organizations(id,name,logo_path)').eq('user_id',uid).eq('active',true).limit(1).maybeSingle();if(error)return toast(error.message);if(!m){$('#auth').hidden=true;$('#onboard').hidden=false;return}org=m.organizations;role=m.role;const{data:p}=await sb.from('plants').select('*').eq('organization_id',m.organization_id).order('created_at').limit(1).single();plant=p;const settingsResult=await sb.from('organization_settings').select('*').eq('organization_id',org.id).maybeSingle();if(settingsResult.data)await applyBranding(settingsResult.data);startApp()}
$('#orgForm').onsubmit=async e=>{e.preventDefault();const{data:r,error}=await sb.rpc('create_organization',{org_name:$('#orgName').value,plant_name:$('#plantName').value});if(error)return toast(error.message);await loadWorkspace()};
function startApp(){$('#auth').hidden=$('#onboard').hidden=true;$('#app').hidden=false;$('#brand').textContent=org.name;if(!$('#plantLabel').textContent)$('#plantLabel').textContent=plant.name;history.replaceState({pmView:'dashboard'},'');renderNav();go('dashboard',true);subscribe();flush()}
$('#logout').onclick=()=>sb.auth.signOut();$('#menu').onclick=()=>{$('#drawer').classList.toggle('open');renderNav()};$('#search').oninput=()=>view==='dashboard'?globalSearch($('#search').value):renderList();$('#add').onclick=()=>openRecordForm();$('#cancelRecord').onclick=$('#closeRecord').onclick=()=>{const m=$('#modal');if(typeof m.close==='function'&&m.open){m.close();m.style.removeProperty('display')}else{m.removeAttribute('open');m.style.display='none'}};
function renderNav(){$$('#drawer [data-view],.mobile-bottom [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#mobileMore')?.classList.toggle('active',$('#drawer')?.classList.contains('open'))}
async function go(v,replace=false){if(!v)return;if(view!==v){viewHistory.push(view);if(!handlingPop){if(replace)history.replaceState({pmView:v},'');else history.pushState({pmView:v},'')}}view=v;$('#drawer').classList.remove('open');const currentSearch=$('#search')||$('#opsSearch');if(currentSearch)currentSearch.value='';renderNav();$('#content').innerHTML=`<div class="card"><h3>Opening ${v==='work'?'Work Orders':v[0].toUpperCase()+v.slice(1)}…</h3></div>`;try{await loadView()}catch(error){console.error(error);$('#content').innerHTML=`<div class="card"><h3>Navigation error</h3><p>${esc(error.message||error)}</p></div>`}}window.go=go;
async function loadView(){if(operations.handles(view))return operations.render(view);ensureCoreToolbar();if(view==='dashboard')return dashboard();if(['people','checklists','maintenance','inventory','notifications'].includes(view))return loadPhase2View();if(['support','manuals','solver','reports'].includes(view))return loadPhase3View();if(['profile','invites','email','qr'].includes(view))return loadPhase4View();if(!['assets','work','files'].includes(view))return settings();$('#toolbar').hidden=false;$('#add').hidden=false;$('#add').textContent=view==='files'?'＋ Upload':'＋ Add';$('#content').innerHTML=`<div class="card"><h3>Loading ${view==='assets'?'assets':view==='work'?'work orders':'files'}…</h3></div>`;try{let result;if(view==='assets')result=await sb.from('assets').select('*').eq('plant_id',plant.id).is('removed_at',null).order('updated_at',{ascending:false}).limit(100);else if(view==='work')result=await sb.from('work_orders').select('*,assets(name)').eq('plant_id',plant.id).is('removed_at',null).order('updated_at',{ascending:false}).limit(100);else result=await sb.from('file_metadata').select('*').eq('organization_id',org.id).is('removed_at',null).order('created_at',{ascending:false}).limit(100);if(result.error)throw result.error;records=result.data||[];renderList();toast(`${view==='assets'?'Assets':view==='work'?'Work Orders':'Files'} opened${records.length?'':'. Tap + Add to create the first record.'}`)}catch(error){console.error('Module load failed',error);records=[];$('#content').innerHTML=`<h1>${view==='assets'?'Assets':view==='work'?'Work Orders':'Files'}</h1><div class="card"><h3>Could not load this module</h3><p>${esc(error.message||error)}</p><button onclick="retryCurrentView()">Retry</button></div>`;toast('Module load error — details are shown on screen')}}
window.retryCurrentView=()=>loadView();
async function dashboard(){
  ensureCoreToolbar();
  const[a,w,f,n,q]=await Promise.all([
    sb.from('assets').select('id,status,running_state',{count:'exact'}).eq('plant_id',plant.id).is('removed_at',null),
    sb.from('work_orders').select('id,status',{count:'exact'}).eq('plant_id',plant.id).is('removed_at',null).neq('status','completed'),
    sb.from('file_metadata').select('id',{count:'exact'}).eq('organization_id',org.id).is('removed_at',null),
    sb.from('notifications').select('id',{count:'exact'}).eq('organization_id',org.id).is('read_at',null),
    allQueued()
  ]);
  const running=(a.data||[]).filter(x=>x.running_state==='running').length;
  $('#toolbar').hidden=false;$('#add').hidden=true;$('#search').placeholder='Search assets, work, manuals, people…';
  const kpi=(label,value,target,cls='')=>`<button type="button" class="kpi kpi-link ${cls}" onclick="window.go('${target}')"><span>${label}</span><strong>${value}</strong><small>Open module →</small></button>`;
  $('#content').innerHTML=`<section class="module-head dashboard-head"><div><h1>Dashboard</h1><p>${esc(org.name)} • ${esc(plant.name)} • ${esc(role)}</p></div><button class="secondary" onclick="window.go('notifications')">🔔 ${(n.count||0)} Alerts</button></section><div class="kpis">${kpi('Assets',a.count||0,'assets')}${kpi('Running',running,'assets','running-kpi')}${kpi('Open Work',w.count||0,'work')}${kpi('Alerts',n.count||0,'notifications','alarm-kpi')}${kpi('Files',f.count||0,'files')}${kpi('Offline Queue',q.length,'settings')}</div><div class="grid dashboard-grid"><button type="button" class="card dashboard-link" onclick="window.go('assets')"><h3>🏭 Assets</h3><p>Equipment register, state and QR records</p><span>Open Assets →</span></button><button type="button" class="card dashboard-link" onclick="window.go('work')"><h3>🧰 Work Orders</h3><p>Assigned corrective work and completion</p><span>Open Work Orders →</span></button><button type="button" class="card dashboard-link" onclick="window.go('notifications')"><h3>🔔 Alarms & Notifications</h3><p>${n.count||0} unread operational alerts</p><span>Open Alerts →</span></button><button type="button" class="card dashboard-link" onclick="window.go('files')"><h3>📎 Files</h3><p>Storage-backed manuals and images</p><span>Open Files →</span></button><button type="button" class="card dashboard-link" onclick="window.go('checklists')"><h3>✅ Checklists</h3><p>Templates and completed runs</p><span>Open Checklists →</span></button><button type="button" class="card dashboard-link" onclick="window.go('maintenance')"><h3>🛠 Maintenance</h3><p>Weekly, monthly and yearly plans</p><span>Open Maintenance →</span></button><button type="button" class="card dashboard-link" onclick="window.go('inventory')"><h3>📦 Spares & Tools</h3><p>Stock, custody and calibration</p><span>Open Inventory →</span></button><button type="button" class="card dashboard-link" onclick="window.go('people')"><h3>👥 People</h3><p>Workers, roster and attendance</p><span>Open People →</span></button><button type="button" class="card dashboard-link" onclick="window.go('support')"><h3>💬 Technical Support</h3><p>Multi-user technical conversations</p><span>Open Support →</span></button><button type="button" class="card dashboard-link" onclick="window.go('manuals')"><h3>📚 Manuals</h3><p>Storage-backed technical documents</p><span>Open Manuals →</span></button><button type="button" class="card dashboard-link" onclick="window.go('solver')"><h3>🧠 Problem Solver</h3><p>Manual, experience and AI-ready diagnosis</p><span>Open Solver →</span></button><button type="button" class="card dashboard-link" onclick="window.go('reports')"><h3>📊 Reports</h3><p>Filters and CSV, Excel, Word, PDF exports</p><span>Open Reports →</span></button></div>`;
}

function settings(){$('#toolbar').hidden=true;$('#content').innerHTML=`<h1>Settings</h1><div class="card"><h3>Workspace</h3><p>Organization: ${esc(org.name)}<br>Plant: ${esc(plant.name)}<br>Role: ${esc(role)}<br>User: ${esc(session?.user?.email||'Signed-in user')}</p><button onclick="location.reload()">Refresh</button></div>`}
function renderList(){if(!['assets','work','files'].includes(view))return;$('#toolbar').hidden=false;$('#add').textContent=view==='files'?'＋ Upload':'＋ Add';const q=$('#search').value.toLowerCase(),list=records.filter(r=>JSON.stringify(r).toLowerCase().includes(q));$('#content').innerHTML=`<h1>${view==='assets'?'Assets':view==='work'?'Work Orders':'Files'}</h1><div class="grid">${list.map(card).join('')||'<div class="card">No records.</div>'}</div>`}
function card(r){if(view==='assets')return`<article class="card"><h3>${esc(r.name)}</h3><p>${esc(r.asset_code)} • ${esc(r.asset_type)}<br>${esc(r.location)}</p><div class="state ${esc(r.running_state)}">● ${esc(r.running_state)}</div><div class="state ${esc(r.status)}">${esc(r.status)}</div><div class="actions"><button onclick="editRecord('${r.id}')">Edit</button>${role==='owner'?`<button class="danger" onclick="removeRecord('${r.id}')">Remove</button>`:''}</div></article>`;if(view==='work')return`<article class="card"><h3>${esc(r.title)}</h3><p>${esc(r.assets?.name||'General')} • ${esc(r.priority)} • ${esc(r.status)}<br>${esc(r.description)}</p>${r.work_done?`<p><b>Work done:</b> ${esc(r.work_done)}<br>${esc(r.designation||'')} • ${esc(r.shift_name||'')} • ${r.completed_at?new Date(r.completed_at).toLocaleString():''}</p>`:''}<div class="actions">${r.status==='completed'?`<button onclick="reopenWork('${r.id}')">Reopen</button>`:`<button class="primary" onclick="completeWork('${r.id}')">✓ Work Done</button>`}<button onclick="editRecord('${r.id}')">Edit</button>${role==='owner'?`<button class="danger" onclick="removeRecord('${r.id}')">Remove</button>`:''}</div></article>`;return`<article class="card"><h3>${esc(r.file_name)}</h3><p>${esc(r.category)} • ${Math.ceil((r.size_bytes||0)/1024)} KB</p><button onclick="downloadFile('${r.object_path}')">Open</button></article>`}
window.editRecord=id=>openRecordForm(records.find(r=>r.id===id));window.removeRecord=async id=>{if(role!=='owner')return toast('Only the owner can remove records');if(!confirm('Move this record to Recovery?'))return;const table=view==='assets'?'assets':'work_orders',record={id,removed_at:new Date().toISOString(),removed_by:userId};if(navigator.onLine){const{error}=await sb.from(table).update(record).eq('id',id);if(error)return toast(error.message)}else await enqueue({table,action:'upsert',record});await operations.audit('record_removed',table,id);toast('Moved to Recovery');loadView()};
function field(name,label,value='',type='text'){return`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" required></label>`}
function openRecordForm(r={}){if(view==='files')return $('#fileInput')?.click()||createFileInput();$('#modalTitle').textContent=r.id?'Edit record':`Add ${view==='assets'?'asset':'work order'}`;if(view==='assets')$('#fields').innerHTML=field('asset_code','Asset code',r.asset_code)+field('name','Name',r.name)+field('asset_type','Type',r.asset_type)+field('location','Location',r.location)+field('manufacturer','Manufacturer',r.manufacturer)+field('model','Model',r.model)+field('serial_number','Serial number',r.serial_number)+field('rating','Rating / capacity',r.rating)+field('status','Status',r.status||'operational')+field('running_state','Running state',r.running_state||'shutdown');else $('#fields').innerHTML=field('title','Title',r.title)+`<label>Description<textarea name="description" required>${esc(r.description)}</textarea></label>`+field('priority','Priority',r.priority||'medium')+field('status','Status',r.status||'open')+field('due_at','Due date',r.due_at?.slice(0,16)||'','datetime-local');formHandler=async values=>{const table=view==='assets'?'assets':'work_orders',base={...r};delete base.assets;const record={...base,...values,id:r.id||crypto.randomUUID(),organization_id:org.id,plant_id:plant.id,created_by:r.created_by||userId,updated_at:new Date().toISOString()};if(navigator.onLine){const{error}=await sb.from(table).upsert(record);if(error)throw error}else await enqueue({table,action:'upsert',record});await operations.audit(r.id?'record_updated':'record_created',table,record.id,{name:record.name||record.title});records=[record,...records.filter(item=>item.id!==record.id)];renderList();toast('Saved successfully');setTimeout(()=>loadView(),250)};const modal=$('#modal');modal.style.removeProperty('display');if(typeof modal.showModal==='function')modal.showModal();else{modal.setAttribute('open','');modal.style.display='block'}}
$('#recordForm').onsubmit=async e=>{e.preventDefault();try{if(!userId){const result=await sb.auth.getUser();userId=result.data.user?.id;if(!userId)throw Error('Your session expired. Please sign in again.')}await formHandler(Object.fromEntries(new FormData(e.target)));if(typeof $('#modal').close==='function')$('#modal').close();else{$('#modal').removeAttribute('open');$('#modal').style.display='none'}}catch(x){console.error('Save failed',x);toast(x.message||String(x))}};
window.completeWork=id=>{const r=records.find(x=>x.id===id);if(!r)return;$('#modalTitle').textContent=`Work Done — ${r.title}`;$('#fields').innerHTML=`<label>Work done<textarea name="work_done" required></textarea></label>${field('shift_name','Shift',profile.default_shift||'General Shift')}${field('designation','Designation',profile.designation||role)}<label>Tools used<textarea name="tools_used"></textarea></label><label>Parts used<textarea name="parts_used"></textarea></label><label>Measurements / readings<textarea name="measurements_text"></textarea></label><label>Root cause<textarea name="root_cause"></textarea></label><label>Corrective action<textarea name="corrective_action"></textarea></label>${field('downtime_minutes','Downtime minutes','0','number')}`;formHandler=async values=>{const completed_at=new Date().toISOString(),measurements={text:values.measurements_text||''};delete values.measurements_text;const update={...values,measurements,downtime_minutes:Number(values.downtime_minutes)||0,status:'completed',completed_by:userId,completed_at,updated_at:completed_at};const q=await sb.from('work_orders').update(update).eq('id',id);if(q.error)throw q.error;await operations.audit('work_order_completed','work_order',id,{title:r.title,shift_name:update.shift_name,designation:update.designation,downtime_minutes:update.downtime_minutes});toast('Work completion recorded');loadView()};const m=$('#modal');m.style.removeProperty('display');m.showModal?m.showModal():m.setAttribute('open','');operations.enhanceVoice(m)};
window.reopenWork=async id=>{if(!['owner','manager','supervisor'].includes(role))return toast('Supervisor permission required to reopen work');if(!confirm('Reopen this completed work order?'))return;const q=await sb.from('work_orders').update({status:'open',updated_at:new Date().toISOString()}).eq('id',id);if(q.error)return toast(q.error.message);await operations.audit('work_order_reopened','work_order',id);toast('Work order reopened');loadView()};
function createFileInput(){const i=document.createElement('input');i.type='file';i.id='fileInput';i.multiple=true;i.hidden=true;i.onchange=()=>uploadFiles(i.files);document.body.append(i);i.click()}
async function uploadFiles(files){for(const file of files){const id=crypto.randomUUID(),path=`${org.id}/${plant.id}/${id}-${file.name.replace(/[^\w.-]/g,'_')}`;const{error}=await sb.storage.from(FILE_BUCKET).upload(path,file);if(error){toast(error.message);continue}await sb.from('file_metadata').insert({id,organization_id:org.id,plant_id:plant.id,bucket:FILE_BUCKET,object_path:path,file_name:file.name,mime_type:file.type,size_bytes:file.size,category:'manual',uploaded_by:userId})}toast('Upload complete');loadView()}
window.downloadFile=async path=>{const{data:d,error}=await sb.storage.from(FILE_BUCKET).createSignedUrl(path,120);if(error)return toast(error.message);open(d.signedUrl,'_blank')};
function realtimeRefresh(table){const modules={assets:'assets',work_orders:'work',notifications:'notifications',checklist_templates:'checklists',checklist_runs:'checklists',maintenance_plans:'maintenance',maintenance_completions:'maintenance',spares:'inventory',tools:'inventory',inventory_transactions:'inventory',tool_transactions:'inventory',support_threads:'support',support_messages:'support',manuals:'manuals',problem_cases:'solver',shift_assignments:'people',attendance:'people',shift_handovers:'people',daily_logs:'people'};if(view!=='dashboard'&&modules[table]!==view)return;clearTimeout(realtimeTimer);realtimeTimer=setTimeout(()=>loadView(),350)}
function subscribe(){
  channel?.unsubscribe();
  const tables=['assets','work_orders','notifications','checklist_templates','checklist_runs','maintenance_plans','maintenance_completions','spares','tools','inventory_transactions','tool_transactions','support_threads','support_messages','manuals','problem_cases','shift_assignments','attendance','shift_handovers','daily_logs'];
  channel=sb.channel(`plant-${plant.id}`,{config:{presence:{key:userId}}});
  tables.forEach(table=>channel.on('postgres_changes',{event:'*',schema:'public',table},()=>realtimeRefresh(table)));
  channel.on('presence',{event:'sync'},()=>{const state=channel.presenceState();onlineUsers=Math.max(1,Object.values(state).reduce((n,list)=>n+list.length,0));setSync()});
  channel.subscribe(status=>{if(status==='SUBSCRIBED')channel.track({user_id:userId,name:profile.full_name||session?.user?.email,plant_id:plant.id,online_at:new Date().toISOString()});if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')setSync()})
}
async function flush(){setSync();const n=await flushQueue(sb);if(n)toast(`${n} offline action(s) synchronized`)}window.addEventListener('online',flush);window.addEventListener('offline',setSync);window.addEventListener('popstate',async e=>{const target=e.state?.pmView;if(!target)return;handlingPop=true;try{view=target;renderNav();await loadView()}finally{handlingPop=false}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=4.5.1',{updateViaCache:'none'});init();

/* Phase 2 modules */
async function loadPhase2View(){
  $('#toolbar').hidden=false;$('#add').hidden=view==='people'||view==='notifications';$('#add').textContent='＋ Add';$('#content').innerHTML=`<div class="card"><h3>Loading ${view}…</h3></div>`;
  try{
    if(view==='people'){const r=await sb.from('organization_members').select('user_id,role,active').eq('organization_id',org.id);if(r.error)throw r.error;const ids=(r.data||[]).map(x=>x.user_id),p=ids.length?await sb.from('profiles').select('id,full_name').in('id',ids):{data:[]};records=(r.data||[]).map(x=>({...x,profile:(p.data||[]).find(y=>y.id===x.user_id)}));return renderPeople()}
    if(view==='checklists'){const r=await sb.from('checklist_templates').select('*,assets(name),checklist_items(count)').eq('plant_id',plant.id).order('updated_at',{ascending:false});if(r.error)throw r.error;records=r.data||[]}
    if(view==='maintenance'){const r=await sb.from('maintenance_plans').select('*,assets(name)').eq('plant_id',plant.id).order('updated_at',{ascending:false});if(r.error)throw r.error;records=r.data||[]}
    if(view==='inventory'){const[a,b]=await Promise.all([sb.from('spares').select('*').eq('plant_id',plant.id),sb.from('tools').select('*').eq('plant_id',plant.id)]);if(a.error)throw a.error;if(b.error)throw b.error;records=[...(a.data||[]).map(x=>({...x,_kind:'spare'})),...(b.data||[]).map(x=>({...x,_kind:'tool'}))]}
    if(view==='notifications'){const r=await sb.from('notifications').select('*').eq('organization_id',org.id).order('created_at',{ascending:false}).limit(100);if(r.error)throw r.error;records=r.data||[];return renderNotifications()}
    renderPhase2List();
  }catch(e){$('#content').innerHTML=`<h1>${view}</h1><div class="card"><h3>Could not load module</h3><p>${esc(e.message)}</p></div>`}
}
function renderPeople(){$('#content').innerHTML=`<h1>Roster & Attendance</h1><div class="grid">${records.map(x=>`<div class="card"><h3>${esc(x.profile?.full_name||x.user_id)}</h3><p>${esc(x.role)} • ${x.active?'Active':'Inactive'}</p></div>`).join('')||'<div class="card">No members.</div>'}</div>`}
function renderNotifications(){$('#content').innerHTML=`<section class="module-head"><div><h1>Alarms & Notifications</h1><p>Checklist failures, maintenance alerts and operational messages</p></div>${records.some(x=>!x.read_at)?'<button onclick="markAllNotificationsRead()">✓ Mark all read</button>':''}</section><div class="grid">${records.map(x=>`<article class="card ${x.read_at?'muted':''}"><div class="record-title"><div><h3>${x.read_at?'':'🔔 '}${esc(x.title)}</h3><p>${new Date(x.created_at).toLocaleString()}</p></div><span class="state ${x.read_at?'read':'alarm'}">${x.read_at?'Read':'Unread'}</span></div><p>${esc(x.body)}</p>${x.read_at?'':`<button onclick="markNotificationRead('${x.id}')">Mark read</button>`}</article>`).join('')||'<div class="empty-state"><b>No alarms</b><p>New operational alerts will appear here.</p></div>'}</div>`}
window.markNotificationRead=async id=>{const r=await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);if(r.error)return toast(r.error.message);toast('Notification marked read');loadView()};
window.markAllNotificationsRead=async()=>{const r=await sb.from('notifications').update({read_at:new Date().toISOString()}).eq('organization_id',org.id).is('read_at',null);if(r.error)return toast(r.error.message);toast('All notifications marked read');loadView()};
function renderPhase2List(){const names={checklists:'Checklists',maintenance:'Maintenance',inventory:'Spares & Tools'};$('#content').innerHTML=`<h1>${names[view]}</h1><div class="grid">${records.map(phase2Card).join('')||'<div class="card">No records. Tap + Add.</div>'}</div>`}
function phase2Card(x){if(view==='checklists')return`<div class="card"><h3>${esc(x.name)}</h3><p>${esc(x.assets?.name||'General')} • ${esc(x.schedule)} • ${esc(x.shift_name)}</p></div>`;if(view==='maintenance')return`<div class="card"><h3>${esc(x.title)}</h3><p>${esc(x.frequency)} • ${esc(x.priority)} • Due ${esc(x.next_due)} • ${esc(x.status)}</p><p>${esc(x.description)}</p></div>`;return x._kind==='spare'?`<div class="card"><h3>${esc(x.description)}</h3><p>${esc(x.part_number)} • Stock ${x.stock} • Min ${x.min_stock} • ${esc(x.bin_location)}</p></div>`:`<div class="card"><h3>${esc(x.name)}</h3><p>${esc(x.tool_code)} • ${esc(x.status)} • Calibration ${esc(x.calibration_due)}</p></div>`}
const addPhase1Handler=$('#add').onclick;$('#add').onclick=()=>{if(['assets','work','files'].includes(view))return openRecordForm();if(view==='checklists')return phase2Form('checklist_templates',[['name','Checklist name'],['schedule','Schedule'],['shift_name','Shift'],['instructions','Instructions']]);if(view==='maintenance')return phase2Form('maintenance_plans',[['title','Title'],['frequency','Frequency'],['priority','Priority'],['next_due','Due date','date'],['description','Description']]);if(view==='inventory')return inventoryChoice()};
function phase2Form(table,fields){$('#modalTitle').textContent='Add '+view;$('#fields').innerHTML=fields.map(f=>field(f[0],f[1],'',f[2]||'text')).join('');formHandler=async values=>{const record={...values,id:crypto.randomUUID(),organization_id:org.id,plant_id:plant.id,created_by:userId,updated_at:new Date().toISOString()};if(['spares','tools'].includes(table))delete record.created_by;if(table==='maintenance_plans')record.status='pending';const r=await sb.from(table).insert(record);if(r.error)throw r.error;toast('Saved');loadPhase2View()};const m=$('#modal');m.style.removeProperty('display');m.showModal?m.showModal():m.setAttribute('open','')}
function inventoryChoice(){const type=confirm('OK = Add Spare, Cancel = Add Tool')?'spares':'tools';const fs=type==='spares'?[['part_number','Part number'],['description','Description'],['stock','Stock','number'],['min_stock','Minimum','number'],['bin_location','Bin location']]:[['tool_code','Tool code'],['name','Name'],['specification','Specification'],['condition','Condition'],['calibration_due','Calibration due','date']];phase2Form(type,fs)}


/* Phase 3 */
async function loadPhase3View(){
 $('#toolbar').hidden=false;$('#add').hidden=view==='reports';$('#add').textContent=view==='manuals'?'＋ Upload':view==='solver'?'＋ New Case':'＋ Add';$('#content').innerHTML=`<div class="card"><h3>Loading ${view}…</h3></div>`;
 try{if(view==='support'){const r=await sb.from('support_threads').select('*,assets(name)').eq('plant_id',plant.id).order('updated_at',{ascending:false});if(r.error)throw r.error;records=r.data||[];renderSupport()}
 else if(view==='manuals'){const r=await sb.from('manuals').select('*,assets(name)').eq('organization_id',org.id).order('created_at',{ascending:false});if(r.error)throw r.error;records=r.data||[];renderManuals()}
 else if(view==='solver'){const r=await sb.from('problem_cases').select('*,assets(name)').eq('plant_id',plant.id).order('created_at',{ascending:false});if(r.error)throw r.error;records=r.data||[];renderSolver()}
 else return renderReports()}catch(e){$('#content').innerHTML=`<h1>${view}</h1><div class="card"><h3>Could not load</h3><p>${esc(e.message)}</p></div>`}}
function renderSupport(){
  $('#content').innerHTML=`<section class="module-head"><div><h1>Technical Support</h1><p>Open plant issues, discuss troubleshooting and preserve the complete conversation.</p></div><button class="primary" onclick="openSupportForm()">＋ New Support Issue</button></section><div class="source-box"><b>How it works:</b> Create an issue, add the first technical message, then workers can open the conversation and reply with voice or text.</div><div class="record-grid support-layout">${records.map(x=>`<article class="record-card"><div class="record-title"><div><h3>${esc(x.subject)}</h3><p>${esc(x.assets?.name||'General plant issue')} • ${new Date(x.updated_at||x.created_at).toLocaleString()}</p></div><span class="state ${esc(x.status)}">${esc(x.status)}</span></div><p>Priority: ${esc(x.priority)}</p><div class="actions"><button class="primary" onclick="openSupport('${x.id}')">Open Conversation</button><button onclick="setSupportStatus('${x.id}','${x.status==='closed'?'open':'closed'}')">${x.status==='closed'?'Reopen':'Close'}</button></div></article>`).join('')||`<div class="empty-state"><b>No support conversations</b><p>Create the first issue and record the symptoms, readings or alarm details.</p><button class="primary" onclick="openSupportForm()">＋ Create Support Issue</button></div>`}</div>`
}
window.openSupportForm=()=>{ensureCoreToolbar();$('#modalTitle').textContent='New Technical Support Issue';$('#fields').innerHTML=field('subject','Issue subject')+`<label>Priority<select name="priority"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select></label><label class="span-2">First message<textarea name="message" placeholder="Describe symptoms, alarms, readings and checks already completed" required></textarea></label>`;formHandler=async values=>{const id=crypto.randomUUID(),stamp=new Date().toISOString();let r=await sb.from('support_threads').insert({id,organization_id:org.id,plant_id:plant.id,subject:values.subject,priority:values.priority,status:'open',created_by:userId,created_at:stamp,updated_at:stamp});if(r.error)throw r.error;r=await sb.from('support_messages').insert({id:crypto.randomUUID(),thread_id:id,user_id:userId,message:values.message,created_at:stamp});if(r.error)throw r.error;await operations.audit('support_issue_created','support_thread',id,{subject:values.subject,priority:values.priority});toast('Support issue created');loadPhase3View()};const m=$('#modal');m.style.removeProperty('display');m.showModal?m.showModal():m.setAttribute('open','');operations.enhanceVoice(m)};
window.openSupport=async id=>{const thread=records.find(x=>x.id===id),r=await sb.from('support_messages').select('*').eq('thread_id',id).order('created_at');if(r.error)return toast(r.error.message);const userIds=[...new Set((r.data||[]).map(x=>x.user_id))],profiles=userIds.length?(await sb.from('profiles').select('id,full_name,designation').in('id',userIds)).data||[]:[];$('#modalTitle').textContent=thread?.subject||'Support conversation';$('#fields').innerHTML=`<div class="span-2 conversation">${(r.data||[]).map(x=>{const p=profiles.find(y=>y.id===x.user_id);return`<div class="message ${x.user_id===userId?'mine':''}">${esc(x.message)}<small>${esc(p?.full_name||'Worker')} • ${esc(p?.designation||'')} • ${new Date(x.created_at).toLocaleString()}</small></div>`}).join('')||'<p>No messages.</p>'}</div><label class="span-2">Reply<textarea name="message" placeholder="Write or dictate a technical reply" required></textarea></label>`;formHandler=async values=>{const stamp=new Date().toISOString(),q=await sb.from('support_messages').insert({id:crypto.randomUUID(),thread_id:id,user_id:userId,message:values.message,created_at:stamp});if(q.error)throw q.error;await sb.from('support_threads').update({updated_at:stamp,status:'open'}).eq('id',id);await operations.audit('support_reply_added','support_thread',id);toast('Reply sent');setTimeout(()=>window.openSupport(id),200)};const m=$('#modal');m.style.removeProperty('display');m.showModal?m.showModal():m.setAttribute('open','');operations.enhanceVoice(m);setTimeout(()=>{const c=m.querySelector('.conversation');if(c)c.scrollTop=c.scrollHeight},0)};
window.setSupportStatus=async(id,status)=>{const r=await sb.from('support_threads').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return toast(r.error.message);await operations.audit(`support_${status}`,'support_thread',id);toast(`Support issue ${status}`);loadPhase3View()};
function renderManuals(){$('#content').innerHTML=`<h1>Manuals & Drawings</h1><div class="grid">${records.map(x=>`<div class="card"><h3>${esc(x.title)}</h3><p>${esc(x.manufacturer)} ${esc(x.model)}<br>${esc(x.assets?.name||'General')} • ${Math.ceil((x.size_bytes||0)/1024)} KB</p><button onclick="openManual('${x.storage_path}')">Open</button></div>`).join('')||'<div class="card">No manuals uploaded.</div>'}</div>`}
window.openManual=async path=>{const r=await sb.storage.from(FILE_BUCKET).createSignedUrl(path,120);if(r.error)return toast(r.error.message);open(r.data.signedUrl,'_blank')};
let solverMode='manual';
function renderSolver(){
  $('#content').innerHTML=`<section class="module-head"><div><h1>Problem Solver</h1><p>Search plant manuals and experience, ask Gemini securely, or continue with Google.</p></div><button class="secondary" onclick="solverHistory()">Case History (${records.length})</button></section><div class="card"><div class="solver-modes"><button class="${solverMode==='manual'?'active':''}" onclick="setSolverMode('manual')">📚 Manual</button><button class="${solverMode==='gemini'?'active':''}" onclick="setSolverMode('gemini')">✦ Gemini</button><button class="${solverMode==='gemini_manual'?'active':''}" onclick="setSolverMode('gemini_manual')">✦＋📚 Gemini + Manual</button><button class="${solverMode==='google'?'active':''}" onclick="setSolverMode('google')">G Google</button></div><div class="solver-search"><input id="solverQuestion" type="search" placeholder="Describe the fault, alarm code, symptoms or readings…"><button class="primary" onclick="runProblemSearch()">Search / Diagnose</button></div><p id="solverModeHelp" class="muted-text">${solverHelp()}</p></div><div id="solverResult" class="solver-result">${records.length?`<div class="card"><b>Recent case:</b> ${esc(records[0].title)} — ${esc(records[0].status)}</div>`:'<div class="empty-state"><b>Ready to troubleshoot</b><p>Select a mode, enter the problem, or use the microphone.</p></div>'}</div>`;operations.enhanceVoice($('#content'));$('#solverQuestion').onkeydown=e=>{if(e.key==='Enter')window.runProblemSearch()}
}
function solverHelp(){return{manual:'Search only uploaded manual text, approved technical experience and verified plant cases.',gemini:'Ask Gemini for a fast safety-focused technical diagnosis. The private key remains in Supabase.',gemini_manual:'Give Gemini the matching plant manuals and approved experience as its allowed source context.',google:'Open a Google technical search in a new browser tab.'}[solverMode]}
window.setSolverMode=mode=>{solverMode=mode;renderSolver();setTimeout(()=>$('#solverQuestion')?.focus(),0)};
async function collectPlantSources(question){const term=question.trim().replace(/[,%()]/g,' ').slice(0,100),[chunks,experiences,cases,manualFiles]=await Promise.all([sb.from('document_chunks').select('content,page_number,manuals(title)').ilike('content',`%${term}%`).limit(8),sb.from('technical_experiences').select('problem,symptoms,root_cause,solution,tools,parts').eq('organization_id',org.id).eq('approved',true).or(`problem.ilike.%${term}%,symptoms.ilike.%${term}%`).limit(8),sb.from('problem_cases').select('title,symptoms,actual_cause,verified_solution').eq('organization_id',org.id).not('verified_solution','is',null).or(`title.ilike.%${term}%,symptoms.ilike.%${term}%`).limit(8),sb.from('manuals').select('title,manufacturer,model,storage_path,status').eq('organization_id',org.id).or(`title.ilike.%${term}%,manufacturer.ilike.%${term}%,model.ilike.%${term}%`).limit(12)]);return{manuals:chunks.data||[],manual_files:manualFiles.data||[],experiences:experiences.data||[],verified_cases:cases.data||[]}}
window.runProblemSearch=async()=>{const question=$('#solverQuestion').value.trim();if(!question)return toast('Describe the problem first');if(solverMode==='google'){open(`https://www.google.com/search?q=${encodeURIComponent(question+' industrial maintenance troubleshooting')}`,'_blank');$('#solverResult').innerHTML=`<div class="card"><h3>Google search opened</h3><p>${esc(question)}</p><p>Check manufacturer and safety sources before acting.</p></div>`;return}const out=$('#solverResult');out.innerHTML='<div class="card"><h3>Searching safely…</h3><p>Checking plant sources and selected diagnostic mode.</p></div>';try{const sources=await collectPlantSources(question);if(solverMode==='manual'){const manualFiles=sources.manual_files.map(x=>`<div class="source-item"><b>📄 ${esc(x.title)}</b><p>${esc(x.manufacturer||'')} ${esc(x.model||'')} • ${esc(x.status||'uploaded')}</p><button onclick="openManual('${x.storage_path}')">Open Manual</button></div>`).join(''),manual=sources.manuals.map(x=>`<div class="source-item"><b>${esc(x.manuals?.title||'Manual')} — page ${esc(x.page_number||'—')}</b><p>${esc(x.content.slice(0,900))}</p></div>`).join(''),exp=sources.experiences.map(x=>`<div class="source-item"><b>Approved experience: ${esc(x.problem)}</b><p><b>Cause:</b> ${esc(x.root_cause)}<br><b>Solution:</b> ${esc(x.solution)}</p></div>`).join(''),cases=sources.verified_cases.map(x=>`<div class="source-item"><b>Verified case: ${esc(x.title)}</b><p><b>Cause:</b> ${esc(x.actual_cause||'')}<br><b>Solution:</b> ${esc(x.verified_solution)}</p></div>`).join('');out.innerHTML=`<div class="card"><h2>Plant-source results</h2><p class="safety-note">⚠ Follow LOTO, isolation, guarding and qualified-person requirements.</p><div class="source-list">${manualFiles+manual+exp+cases||'<p>No extracted manual text or approved matching experience was found. Upload/extract a manual or try Gemini.</p>'}</div></div>`;return}
  const mode=solverMode==='gemini_manual'?'manual':'quick',functionBody={mode,question,organization_id:org.id,plant_id:plant.id,manuals:sources.manuals,approved_experiences:sources.experiences,verified_cases:sources.verified_cases};let invoke=await sb.functions.invoke('gemini-problem-solver',{body:functionBody});if(invoke.error)invoke=await sb.functions.invoke('smart-responder',{body:functionBody});if(invoke.error)throw Error(`${invoke.error.message}. Deploy smart-responder or gemini-problem-solver and set GEMINI_API_KEY.`);const answer=invoke.data||{};if(answer.error)throw Error(answer.error);out.innerHTML=`<div class="card"><div class="record-title"><div><h2>Gemini diagnosis</h2><p>${solverMode==='gemini_manual'?'Gemini + plant manuals':'Gemini fast answer'}</p></div><span class="state">${esc(answer.confidence||'Unverified')}</span></div><div class="source-box"><b>Safety</b><p>${esc(answer.safety||'Follow plant safety procedures, isolation and qualified-person requirements.')}</p></div><div class="answer-text">${esc(answer.answer||'No answer returned').replaceAll('\n','<br>')}</div><h3>Sources</h3><ul>${(answer.sources||[]).map(x=>`<li>${esc(x)}</li>`).join('')||'<li>No source list returned — verify before action.</li>'}</ul><button onclick="saveSolverCase()">Save as Problem Case</button></div>`;window.lastSolverAnswer={question,mode:solverMode,answer}}catch(e){out.innerHTML=`<div class="error-state"><h2>Diagnosis unavailable</h2><p>${esc(e.message)}</p><button onclick="runProblemSearch()">Retry</button></div>`}}
window.saveSolverCase=async()=>{const x=window.lastSolverAnswer;if(!x)return;const r=await sb.from('problem_cases').insert({id:crypto.randomUUID(),organization_id:org.id,plant_id:plant.id,title:x.question.slice(0,120),symptoms:x.question,mode:x.mode,ai_answer:x.answer,status:'open',created_by:userId,created_at:new Date().toISOString()});if(r.error)return toast(r.error.message);await operations.audit('problem_case_saved','problem_case',r.data?.id||'new',{mode:x.mode});toast('Problem case saved');loadPhase3View()};
window.solverHistory=()=>{$('#solverResult').innerHTML=`<div class="record-grid">${records.map(x=>`<article class="record-card"><h3>${esc(x.title)}</h3><p>${esc(x.symptoms)}<br>${esc(x.mode)} • ${esc(x.status)}</p>${x.verified_solution?`<div class="source-box"><b>Verified solution</b><p>${esc(x.verified_solution)}</p></div>`:''}</article>`).join('')||'<div class="empty-state">No saved cases.</div>'}</div>`};
let reportRows=[],reportTable='work_orders';
const reportTables=['assets','work_orders','checklist_runs','maintenance_plans','spares','tools','support_threads','manuals','problem_cases','attendance','daily_logs','shift_handovers'];
async function renderReports(){
  $('#toolbar').hidden=true;
  $('#content').innerHTML=`<section class="module-head"><div><h1>Reports & Analytics</h1><p>Generate once, then view or download the selected report format.</p></div><button class="secondary" onclick="window.go('dashboard')">Dashboard</button></section><div class="report-controls card"><label>Report module<select id="reportModule">${reportTables.map(t=>`<option value="${t}" ${t===reportTable?'selected':''}>${t.replaceAll('_',' ')}</option>`).join('')}</select></label><label>From date<input id="reportFrom" type="date"></label><label>To date<input id="reportToDate" type="date"></label><button class="primary" onclick="loadReportPreview()">Generate Report</button></div><div class="format-grid">${['csv','excel','word','pdf'].map(t=>`<article class="format-card"><div><b>${t.toUpperCase()}</b><small>${t==='csv'?'Data table':t==='excel'?'Spreadsheet':t==='word'?'Document':'Print-ready report'}</small></div><button onclick="viewReport('${t}')">View</button><button class="primary" onclick="exportReport('${t}')">Download</button></article>`).join('')}</div><div id="reportPreview">${emptyReport('Select a module and tap Generate Report. Reports now load only the selected module.')}</div>`;
}
function emptyReport(message){return `<div class="empty-state"><b>Report preview</b><p>${esc(message)}</p></div>`}
window.loadReportPreview=async()=>{
  reportTable=$('#reportModule').value;const from=$('#reportFrom').value,to=$('#reportToDate').value;
  $('#reportPreview').innerHTML='<div class="card loading-card"><span class="spinner"></span><div><h3>Generating report</h3><p>Loading the selected module…</p></div></div>';
  try{const request=sb.from(reportTable).select('*').eq('organization_id',org.id).limit(1000),timeout=new Promise((_,reject)=>setTimeout(()=>reject(Error('Report request timed out. Check the connection and retry.')),15000)),r=await Promise.race([request,timeout]);if(r.error)throw r.error;
  reportRows=(r.data||[]).filter(row=>{const raw=row.created_at||row.updated_at||row.performed_at||row.completed_at||row.work_date||row.log_date||row.next_due;if(!raw||(!from&&!to))return true;const d=String(raw).slice(0,10);return(!from||d>=from)&&(!to||d<=to)});paintReportPreview();toast(`Report generated: ${reportRows.length} record(s)`)}catch(error){reportRows=[];$('#reportPreview').innerHTML=`<div class="error-state"><h2>Report could not load</h2><p>${esc(error.message)}</p><button onclick="loadReportPreview()">Retry</button></div>`}
};
function paintReportPreview(){if(!reportRows.length){$('#reportPreview').innerHTML=emptyReport('No records match the selected module and dates.');return}const keys=reportKeys();$('#reportPreview').innerHTML=`<div class="report-summary"><b>${reportRows.length} record(s)</b><span>${esc(reportTable.replaceAll('_',' '))}</span></div><div class="table-wrap"><table><thead><tr>${keys.map(k=>`<th>${esc(k.replaceAll('_',' '))}</th>`).join('')}</tr></thead><tbody>${reportRows.slice(0,100).map(row=>`<tr>${keys.map(k=>`<td>${esc(reportValue(row[k]))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${reportRows.length>100?'<p class="muted-text">Preview shows 100 rows; downloads contain all rows.</p>':''}`}
function reportKeys(){const preferred=['created_at','updated_at','work_date','log_date','title','name','asset_code','status','priority','shift_name','worker_name','designation','description','work_done'];const all=[...new Set(reportRows.flatMap(r=>Object.keys(r)))].filter(k=>!['organization_id','plant_id','signature_data'].includes(k));return[...preferred.filter(k=>all.includes(k)),...all.filter(k=>!preferred.includes(k))].slice(0,18)}
function reportValue(v){if(v==null)return'';if(typeof v==='object')return JSON.stringify(v);return String(v)}
function reportCSV(){const keys=reportKeys();return[keys.join(','),...reportRows.map(r=>keys.map(k=>`"${reportValue(r[k]).replaceAll('"','""')}"`).join(','))].join('\r\n')}
function reportHTML(format='report'){const keys=reportKeys(),title=`${org.name} — ${plant.name} — ${reportTable.replaceAll('_',' ')}`;return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(title)}</title><style>body{font:12px Arial;margin:28px;color:#111}h1{font-size:21px}.meta{margin-bottom:16px;color:#555}.badge{padding:4px 8px;background:#e8f1fa;border-radius:6px}table{border-collapse:collapse;width:100%}th,td{border:1px solid #8594a3;padding:6px;text-align:left;vertical-align:top}th{background:#dfeaf5}@media print{button{display:none}}</style></head><body><h1>${esc(title)}</h1><div class="meta">Generated ${new Date().toLocaleString()} • ${reportRows.length} record(s) • <span class="badge">${format.toUpperCase()} view</span></div><table><thead><tr>${keys.map(k=>`<th>${esc(k.replaceAll('_',' '))}</th>`).join('')}</tr></thead><tbody>${reportRows.map(r=>`<tr>${keys.map(k=>`<td>${esc(reportValue(r[k]))}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`}
function saveReportBlob(data,type,extension){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=`PlantMaster-${reportTable}-${new Date().toISOString().slice(0,10)}.${extension}`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.viewReport=type=>{if(!reportRows.length)return toast('Generate the report first');if(type==='csv'){$('#reportPreview').innerHTML=`<div class="report-summary"><b>CSV view</b><button onclick="paintReportPreview()">Table view</button></div><pre class="csv-view">${esc(reportCSV())}</pre>`;return}const w=open('','_blank');if(!w)return toast('Allow pop-ups to view this format');w.document.write(reportHTML(type));if(type==='pdf')w.document.write('<p><button onclick="print()">Print / Save PDF</button></p>');w.document.close()};
window.exportReport=type=>{if(!reportRows.length)return toast('Generate the report first');if(type==='csv')saveReportBlob('\ufeff'+reportCSV(),'text/csv;charset=utf-8','csv');if(type==='excel')saveReportBlob('\ufeff'+reportHTML('excel'),'application/vnd.ms-excel','xls');if(type==='word')saveReportBlob(reportHTML('word'),'application/msword','doc');if(type==='pdf'){const w=open('','_blank');if(!w)return toast('Allow pop-ups to save PDF');w.document.write(reportHTML('pdf'));w.document.close();setTimeout(()=>w.print(),350)}toast(type==='pdf'?'Print dialog opened — choose Save as PDF':`${type.toUpperCase()} downloaded`)};

const addPhase2Click=$('#add').onclick;$('#add').onclick=()=>{if(view==='support')return phase3Form('support_threads',[['subject','Subject'],['priority','Priority']]);if(view==='solver')return phase3Form('problem_cases',[['title','Problem title'],['symptoms','Symptoms'],['alarm_code','Alarm code']]);if(view==='manuals')return createManualInput();return ['assets','work','files'].includes(view)?openRecordForm():view==='checklists'?phase2Form('checklist_templates',[['name','Checklist name'],['schedule','Schedule'],['shift_name','Shift'],['instructions','Instructions']]):view==='maintenance'?phase2Form('maintenance_plans',[['title','Title'],['frequency','Frequency'],['priority','Priority'],['next_due','Due date','date'],['description','Description']]):view==='inventory'?inventoryChoice():null};
function phase3Form(table,fields){$('#modalTitle').textContent='Add '+view;$('#fields').innerHTML=fields.map(f=>field(f[0],f[1],'',f[2]||'text')).join('');formHandler=async values=>{const r={...values,id:crypto.randomUUID(),organization_id:org.id,plant_id:plant.id,created_by:userId,updated_at:new Date().toISOString()};if(table==='support_threads')r.status='open';if(table==='problem_cases'){r.status='open';r.mode='offline'}const q=await sb.from(table).insert(r);if(q.error)throw q.error;toast('Saved');loadPhase3View()};const m=$('#modal');m.style.removeProperty('display');m.showModal?m.showModal():m.setAttribute('open','')}
function createManualInput(){const i=document.createElement('input');i.type='file';i.accept='.pdf,.doc,.docx,image/*';i.onchange=()=>uploadManual(i.files[0]);i.click()}
async function uploadManual(file){if(!file)return;const id=crypto.randomUUID(),path=`${org.id}/${plant.id}/manuals/${id}-${file.name.replace(/[^\w.-]/g,'_')}`;const u=await sb.storage.from(FILE_BUCKET).upload(path,file);if(u.error)return toast(u.error.message);const r=await sb.from('manuals').insert({id,organization_id:org.id,plant_id:plant.id,title:file.name,storage_path:path,mime_type:file.type,size_bytes:file.size,uploaded_by:userId});if(r.error)return toast(r.error.message);toast('Manual uploaded');loadPhase3View()}



async function applyBranding(x={}){
  const palettes={industrial:['#0ea5e9','#22d3ee'],corporate:['#2563eb','#7c3aed'],green:['#059669','#84cc16'],steel:['#64748b','#38bdf8'],light:['#2563eb','#0891b2']};
  const fallback=palettes[x.theme]||palettes.industrial,primary=x.primary_color||fallback[0],secondary=x.secondary_color||fallback[1];
  document.documentElement.style.setProperty('--brand-primary',primary);document.documentElement.style.setProperty('--brand-secondary',secondary);
  document.body.dataset.theme=x.theme||'industrial';document.body.dataset.pattern=x.pattern||'grid';
  document.title=x.app_name||'PlantMaster Pro';if($('#plantLabel'))$('#plantLabel').textContent=x.plant_display_name||plant?.name||'';
  if(x.logo_path&&$('#brandLogo')){const r=await sb.storage.from(FILE_BUCKET).createSignedUrl(x.logo_path,3600);if(!r.error){$('#brandLogo').src=r.data.signedUrl;$('#brandLogo').hidden=false}}
}
async function renderCompanyProfile(){
  const r=await sb.from('organization_settings').select('*').eq('organization_id',org.id).maybeSingle();if(r.error)return $('#content').innerHTML=`<div class="error-state"><h2>Profile could not load</h2><p>${esc(r.error.message)}</p></div>`;const x=r.data||{};
  let logo='';if(x.logo_path){const u=await sb.storage.from(FILE_BUCKET).createSignedUrl(x.logo_path,900);logo=u.data?.signedUrl||''}
  const opts=(list,current)=>list.map(v=>`<option value="${v}" ${v===(current||'')?'selected':''}>${v[0].toUpperCase()+v.slice(1)}</option>`).join('');
  $('#content').innerHTML=`<section class="module-head"><div><h1>Company Profile & Theme</h1><p>Changes apply immediately to this company workspace and document branding.</p></div><button class="secondary" onclick="window.go('dashboard')">Dashboard</button></section><div class="card profile-shell"><div class="logo-panel"><div id="companyLogoPreview" class="logo-preview">${logo?`<img src="${logo}" alt="Company logo">`:'<span>No logo uploaded</span>'}</div><label class="form-field"><span>Company logo</span><input id="setLogo" type="file" accept="image/png,image/jpeg,image/webp"></label></div><form id="companyProfileForm" class="profile-form"><label class="form-field"><span>Application name</span><input id="setApp" value="${esc(x.app_name||'PlantMaster Pro')}" required></label><label class="form-field"><span>Plant display name</span><input id="setPlant" value="${esc(x.plant_display_name||plant.name)}" required></label><label class="form-field color-field"><span>Primary colour</span><input id="setPrimary" type="color" value="${esc(x.primary_color||'#0ea5e9')}"></label><label class="form-field color-field"><span>Secondary colour</span><input id="setSecondary" type="color" value="${esc(x.secondary_color||'#22d3ee')}"></label><label class="form-field"><span>Theme</span><select id="setTheme">${opts(['industrial','corporate','green','steel','light'],x.theme||'industrial')}</select></label><label class="form-field"><span>Pattern</span><select id="setPattern">${opts(['grid','dots','diagonal','circuit','none'],x.pattern||'grid')}</select></label><label class="form-field span-2"><span>Company address</span><textarea id="setAddress">${esc(x.address||'')}</textarea></label><label class="form-field"><span>Contact number</span><input id="setContact" value="${esc(x.contact||'')}"></label><label class="form-field"><span>Company email</span><input id="setEmail" type="email" value="${esc(x.email||'')}"></label><label class="form-field"><span>Daily report time</span><input id="setReportTime" type="time" value="${esc(String(x.report_time||'11:00').slice(0,5))}"></label><label class="form-field"><span>Document footer</span><input id="setFooter" value="${esc(x.footer_text||'')}"></label><div class="theme-preview"><b>Live theme preview</b><p>Buttons, highlights, patterns and documents use your selected company colours.</p></div><div class="span-2 actions"><button type="submit" class="primary">Save & Apply Profile</button></div></form></div>`;
  $('#setLogo').onchange=e=>{const f=e.target.files[0];if(f)$('#companyLogoPreview').innerHTML=`<img src="${URL.createObjectURL(f)}" alt="Logo preview">`};
  const live=()=>applyBranding({primary_color:$('#setPrimary').value,secondary_color:$('#setSecondary').value,pattern:$('#setPattern').value,theme:$('#setTheme').value,plant_display_name:$('#setPlant').value,app_name:$('#setApp').value});['setPrimary','setSecondary','setPattern'].forEach(id=>$('#'+id).oninput=live);$('#setTheme').onchange=()=>{const palettes={industrial:['#0ea5e9','#22d3ee'],corporate:['#2563eb','#7c3aed'],green:['#059669','#84cc16'],steel:['#64748b','#38bdf8'],light:['#2563eb','#0891b2']},p=palettes[$('#setTheme').value];$('#setPrimary').value=p[0];$('#setSecondary').value=p[1];live()};
  $('#companyProfileForm').onsubmit=saveCompanyProfile;
  operations.enhanceVoice($('#content'));
}
async function saveCompanyProfile(e){
  e.preventDefault();const button=e.submitter;button.disabled=true;button.textContent='Saving…';try{let logo_path;const file=$('#setLogo').files[0];if(file){if(file.size>5*1024*1024)throw Error('Logo must be smaller than 5 MB');logo_path=`${org.id}/branding/${crypto.randomUUID()}-${file.name.replace(/[^\w.-]/g,'_')}`;const u=await sb.storage.from(FILE_BUCKET).upload(logo_path,file);if(u.error)throw u.error}
  const payload={organization_id:org.id,app_name:$('#setApp').value.trim(),plant_display_name:$('#setPlant').value.trim(),primary_color:$('#setPrimary').value,secondary_color:$('#setSecondary').value,theme:$('#setTheme').value,pattern:$('#setPattern').value,address:$('#setAddress').value.trim(),contact:$('#setContact').value.trim(),email:$('#setEmail').value.trim(),report_time:$('#setReportTime').value||'11:00',footer_text:$('#setFooter').value.trim(),updated_at:new Date().toISOString()};if(logo_path)payload.logo_path=logo_path;const r=await sb.from('organization_settings').upsert(payload);if(r.error)throw r.error;await applyBranding(payload);await operations.audit('company_profile_updated','organization',org.id,{theme:payload.theme,pattern:payload.pattern});toast('Company profile saved and applied');await renderCompanyProfile()}catch(error){toast(error.message)}finally{button.disabled=false;button.textContent='Save & Apply Profile'}}

/* Phase 4 */
async function loadPhase4View(){
 $('#toolbar').hidden=true;if(view==='profile')return renderCompanyProfile();try{
 if(view==='profile'){const r=await sb.from('organization_settings').select('*').eq('organization_id',org.id).maybeSingle();const x=r.data||{};$('#content').innerHTML=`<h1>Company Profile & Theme</h1><div class="card"><label>Company logo</label><input id="setLogo" type="file" accept="image/*"><label>App name</label><input id="setApp" value="${esc(x.app_name||'PlantMaster Pro')}"><label>Plant display name</label><input id="setPlant" value="${esc(x.plant_display_name||plant.name)}"><label>Primary colour</label><input id="setPrimary" type="color" value="${esc(x.primary_color||'#3b82f6')}"><label>Secondary colour</label><input id="setSecondary" type="color" value="${esc(x.secondary_color||'#06b6d4')}"><label>Theme</label><select id="setTheme"><option>industrial</option><option>corporate</option><option>green</option><option>steel</option><option>light</option></select><label>Pattern</label><select id="setPattern"><option>grid</option><option>dots</option><option>diagonal</option><option>circuit</option><option>none</option></select><label>Address</label><input id="setAddress" value="${esc(x.address||'')}"><label>Contact</label><input id="setContact" value="${esc(x.contact||'')}"><label>Email</label><input id="setEmail" value="${esc(x.email||'')}"><button onclick="saveOrgSettings()">Save Profile</button></div>`}
 if(view==='invites'){const r=await sb.from('invitations').select('*').eq('organization_id',org.id).order('created_at',{ascending:false});records=r.data||[];$('#content').innerHTML=`<h1>Invitations</h1><button onclick="createInvite()">＋ Invite User</button><div class="grid">${records.map(i=>`<div class="card"><h3>${esc(i.email||'QR Invite')}</h3><p>${esc(i.role)} • Expires ${i.expires_at}</p><div class="invite-actions"><button class="email-btn" onclick="emailInvitation('${i.id}')">✉ Email</button><button class="whatsapp-btn" onclick="whatsappInvitation('${i.id}')">◉ WhatsApp</button><button onclick="shareInvite('${i.token}')">Copy / Share</button></div></div>`).join('')}</div>`}
 if(view==='qr'){$('#content').innerHTML=`<h1>QR Scanner & Generator</h1><div class="grid"><div class="card"><h3>Scan QR</h3><div id="qrReader"></div><button onclick="startQRScanner()">Start Camera</button></div><div class="card"><h3>Generate QR</h3><input id="qrText" placeholder="Asset ID, URL or text"><button onclick="generateQR()">Generate</button><div id="qrOutput"></div></div></div>`}
 if(view==='email'){$('#content').innerHTML=`<h1>Daily Email Sign-off</h1><div class="card"><label>Recipient</label><input id="reportTo"><label>Summary</label><textarea id="reportSummary"></textarea><button onclick="sendDailyReport()">Open Email App</button></div>`}
 }catch(e){$('#content').innerHTML=`<div class="card"><h3>Error</h3><p>${esc(e.message)}</p></div>`}}
window.saveOrgSettings=async()=>{let logo_path;const file=$('#setLogo').files[0];if(file){logo_path=`${org.id}/branding/${crypto.randomUUID()}-${file.name.replace(/[^\w.-]/g,'_')}`;const u=await sb.storage.from(FILE_BUCKET).upload(logo_path,file);if(u.error)return toast(u.error.message)}const payload={organization_id:org.id,app_name:$('#setApp').value,plant_display_name:$('#setPlant').value,primary_color:$('#setPrimary').value,secondary_color:$('#setSecondary').value,theme:$('#setTheme').value,pattern:$('#setPattern').value,address:$('#setAddress').value,contact:$('#setContact').value,email:$('#setEmail').value,updated_at:new Date().toISOString()};if(logo_path)payload.logo_path=logo_path;const r=await sb.from('organization_settings').upsert(payload);if(r.error)return toast(r.error.message);toast('Company profile saved')};
window.createInvite=async()=>{const email=prompt('Invite email (optional for QR):'),role=prompt('Role: manager, engineer, supervisor, technician, store, viewer','technician');if(!role)return;const r=await sb.from('invitations').insert({organization_id:org.id,plant_id:plant.id,email,role,created_by:userId}).select().single();if(r.error)return toast(r.error.message);shareInvite(r.data.token);loadPhase4View()};
window.shareInvite=token=>{const link=`${location.origin}${location.pathname}?invite=${token}`;navigator.share?navigator.share({title:'PlantMaster Invitation',text:`Join ${org.name}`,url:link}):navigator.clipboard.writeText(link).then(()=>toast('Invite link copied'))};
function invitationMessage(i){const p=i.worker_details||{},link=`${location.origin}${location.pathname}?invite=${i.token}`;return{p,link,text:`PlantMaster worker account\nCompany: ${org.name}\nWorker: ${p.full_name||i.email||''}\nRole: ${i.role}\nOpen this secure link to create/sign in to your account:\n${link}`}}
window.emailInvitation=id=>{const i=records.find(x=>x.id===id);if(!i?.email)return toast('This invitation has no email address');const m=invitationMessage(i);location.href=`mailto:${encodeURIComponent(i.email)}?subject=${encodeURIComponent(`Join ${org.name} on PlantMaster`)}&body=${encodeURIComponent(m.text)}`};
window.whatsappInvitation=id=>{const i=records.find(x=>x.id===id);if(!i)return;const m=invitationMessage(i);let phone=String(m.p.contact||'').replace(/\D/g,'');if(!phone)phone=String(prompt('WhatsApp number with country code, for example 923001234567:')||'').replace(/\D/g,'');if(phone)open(`https://wa.me/${phone}?text=${encodeURIComponent(m.text)}`,'_blank')};
window.sendDailyReport=()=>{const to=$('#reportTo').value,summary=$('#reportSummary').value,body=`${org.name} — ${plant.name}\nDate: ${new Date().toLocaleDateString()}\n${summary}`;location.href=`mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent('PlantMaster Daily Report')}&body=${encodeURIComponent(body)}`};


async function globalSearch(q){if(!q.trim())return dashboard();const pattern=`%${q.trim()}%`,[a,w,m]=await Promise.all([sb.from('assets').select('id,name,asset_code,asset_type').eq('plant_id',plant.id).or(`name.ilike.${pattern},asset_code.ilike.${pattern},asset_type.ilike.${pattern}`),sb.from('work_orders').select('id,title,description').eq('plant_id',plant.id).or(`title.ilike.${pattern},description.ilike.${pattern}`),sb.from('manuals').select('id,title,manufacturer,model').eq('organization_id',org.id).or(`title.ilike.${pattern},manufacturer.ilike.${pattern},model.ilike.${pattern}`)]);$('#content').innerHTML=`<h1>Search Results</h1><div class="grid">${(a.data||[]).map(x=>`<div class="card"><h3>🏭 ${esc(x.name)}</h3><p>${esc(x.asset_code)} • ${esc(x.asset_type)}</p></div>`).join('')}${(w.data||[]).map(x=>`<div class="card"><h3>🧰 ${esc(x.title)}</h3><p>${esc(x.description)}</p></div>`).join('')}${(m.data||[]).map(x=>`<div class="card"><h3>📚 ${esc(x.title)}</h3><p>${esc(x.manufacturer)} ${esc(x.model)}</p></div>`).join('')||'<div class="card">No results.</div>'}</div>`}
async function loadQRLib(url,test){if(test())return true;return new Promise(ok=>{const s=document.createElement('script');s.src=url;s.onload=()=>ok(test());s.onerror=()=>ok(false);document.head.append(s)})}
window.generateQR=async()=>{if(!await loadQRLib('https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js',()=>!!window.QRCode))return toast('QR library unavailable');$('#qrOutput').innerHTML='';new QRCode($('#qrOutput'),{text:$('#qrText').value||location.href,width:220,height:220})};
window.startQRScanner=async()=>{if(!isSecureContext)return toast('Camera requires HTTPS');if(!await loadQRLib('https://cdn.jsdelivr.net/npm/html5-qrcode@2.3.8/html5-qrcode.min.js',()=>!!window.Html5Qrcode))return toast('Scanner unavailable');$('#qrReader').innerHTML='';const q=new Html5Qrcode('qrReader');q.start({facingMode:'environment'},{fps:10,qrbox:220},text=>{toast(`Scanned: ${text}`);q.stop()},()=>{}).catch(e=>toast(String(e)))};
