import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';import{SUPABASE_URL,SUPABASE_ANON_KEY,FILE_BUCKET}from'./config.js?v=4.0.7';import{enqueue,flushQueue,allQueued}from'./offline.js?v=4.0.7';
const sb=createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));let session,userId=null,org,plant,role,view='dashboard',records=[],channel,formHandler;
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(x.t);x.t=setTimeout(()=>x.classList.remove('show'),2500)}
function setSync(){const x=$('#sync');x.textContent=navigator.onLine?'● Online':'● Offline';x.style.color=navigator.onLine?'#32d39a':'#fbbf24'}
async function init(){setSync();const{data}=await sb.auth.getSession();session=data.session;$('#boot').hidden=true;if(!session)return showAuth();await loadWorkspace()}
function showAuth(){$('#auth').hidden=false;$('#app').hidden=true}
function authCredentials(){const email=$('#email').value.trim(),password=$('#password').value;if(!email){$('#authMsg').textContent='Enter your work email first.';$('#email').focus();return null}if(!/^\S+@\S+\.\S+$/.test(email)){ $('#authMsg').textContent='Enter a valid email address.';return null}if(password.length<8){$('#authMsg').textContent='Password must contain at least 8 characters.';$('#password').focus();return null}return{email,password}}
$('#authForm').onsubmit=async e=>{e.preventDefault();const credentials=authCredentials();if(!credentials)return;$('#authMsg').textContent='Signing in…';const{error}=await sb.auth.signInWithPassword(credentials);$('#authMsg').textContent=error?.message||''};
$('#signUp').onclick=async()=>{const credentials=authCredentials();if(!credentials)return;$('#authMsg').textContent='Creating account…';const{data:result,error}=await sb.auth.signUp({email:credentials.email,password:credentials.password,options:{emailRedirectTo:location.origin+location.pathname}});if(error){$('#authMsg').textContent=error.message;return}$('#authMsg').textContent=result.session?'Account created and signed in.':'Account created. Check your email confirmation link, then return and sign in.'};
sb.auth.onAuthStateChange(async(_,s)=>{session=s;if(s)await loadWorkspace();else showAuth()});
async function loadWorkspace(){let authUser=session?.user;if(!authUser){const result=await sb.auth.getUser();authUser=result.data.user;}const uid=authUser?.id;if(!uid){showAuth();return}userId=uid;await sb.from('profiles').upsert({id:uid,full_name:authUser.user_metadata?.full_name||authUser.email||''});const{data:m,error}=await sb.from('organization_members').select('organization_id,role,organizations(id,name,logo_path)').eq('user_id',uid).eq('active',true).limit(1).maybeSingle();if(error)return toast(error.message);if(!m){$('#auth').hidden=true;$('#onboard').hidden=false;return}org=m.organizations;role=m.role;const{data:p}=await sb.from('plants').select('*').eq('organization_id',m.organization_id).order('created_at').limit(1).single();plant=p;startApp()}
$('#orgForm').onsubmit=async e=>{e.preventDefault();const{data:r,error}=await sb.rpc('create_organization',{org_name:$('#orgName').value,plant_name:$('#plantName').value});if(error)return toast(error.message);await loadWorkspace()};
function startApp(){$('#auth').hidden=$('#onboard').hidden=true;$('#app').hidden=false;$('#brand').textContent=org.name;$('#plantLabel').textContent=plant.name;renderNav();go('dashboard');subscribe();flush()}
$('#logout').onclick=()=>sb.auth.signOut();$('#menu').onclick=()=>$('#drawer').classList.toggle('open');$('#search').oninput=()=>renderList();$('#add').onclick=()=>openRecordForm();
function renderNav(){$$('#drawer [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}document.addEventListener('click',e=>{const target=e.target.closest('[data-view]');if(!target)return;e.preventDefault();go(target.dataset.view)});
function go(v){if(!v)return;view=v;$('#drawer').classList.remove('open');$('#search').value='';renderNav();loadView()}window.go=go;
async function loadView(){if(view==='dashboard')return dashboard();if(!['assets','work','files'].includes(view))return settings();$('#toolbar').hidden=false;$('#add').textContent=view==='files'?'＋ Upload':'＋ Add';$('#content').innerHTML=`<div class="card"><h3>Loading ${view==='assets'?'assets':view==='work'?'work orders':'files'}…</h3></div>`;try{let result;if(view==='assets')result=await sb.from('assets').select('*').eq('plant_id',plant.id).order('updated_at',{ascending:false}).limit(100);else if(view==='work')result=await sb.from('work_orders').select('*,assets(name)').eq('plant_id',plant.id).order('updated_at',{ascending:false}).limit(100);else result=await sb.from('file_metadata').select('*').eq('organization_id',org.id).order('created_at',{ascending:false}).limit(100);if(result.error)throw result.error;records=result.data||[];renderList();toast(`${view==='assets'?'Assets':view==='work'?'Work Orders':'Files'} opened${records.length?'':'. Tap + Add to create the first record.'}`)}catch(error){console.error('Module load failed',error);records=[];$('#content').innerHTML=`<h1>${view==='assets'?'Assets':view==='work'?'Work Orders':'Files'}</h1><div class="card"><h3>Could not load this module</h3><p>${esc(error.message||error)}</p><button onclick="retryCurrentView()">Retry</button></div>`;toast('Module load error — details are shown on screen')}}
window.retryCurrentView=()=>loadView();
async function dashboard(){const[a,w,f,q]=await Promise.all([sb.from('assets').select('id,status,running_state',{count:'exact'}).eq('plant_id',plant.id),sb.from('work_orders').select('id,status',{count:'exact'}).eq('plant_id',plant.id).neq('status','completed'),sb.from('file_metadata').select('id',{count:'exact'}).eq('organization_id',org.id),allQueued()]);$('#toolbar').hidden=true;$('#content').innerHTML=`<h1>Dashboard</h1><p>${esc(org.name)} • ${esc(plant.name)} • ${esc(role)}</p><div class="kpis"><div class="kpi"><span>Assets</span><strong>${a.count||0}</strong></div><div class="kpi"><span>Open Work</span><strong>${w.count||0}</strong></div><div class="kpi"><span>Files</span><strong>${f.count||0}</strong></div><div class="kpi"><span>Offline Queue</span><strong>${q.length}</strong></div></div><div class="grid"><button type="button" class="card dashboard-link" data-view="assets"><h3>🏭 Assets</h3><p>Multi-user equipment register</p></button><button type="button" class="card dashboard-link" data-view="work"><h3>🧰 Work Orders</h3><p>Assigned corrective work</p></button><button type="button" class="card dashboard-link" data-view="files"><h3>📎 Files</h3><p>Storage-backed manuals and images</p></button></div>`}
function settings(){$('#toolbar').hidden=true;$('#content').innerHTML=`<h1>Settings</h1><div class="card"><h3>Workspace</h3><p>Organization: ${esc(org.name)}<br>Plant: ${esc(plant.name)}<br>Role: ${esc(role)}<br>User: ${esc(session?.user?.email||'Signed-in user')}</p><button onclick="location.reload()">Refresh</button></div>`}
function renderList(){if(!['assets','work','files'].includes(view))return;$('#toolbar').hidden=false;$('#add').textContent=view==='files'?'＋ Upload':'＋ Add';const q=$('#search').value.toLowerCase(),list=records.filter(r=>JSON.stringify(r).toLowerCase().includes(q));$('#content').innerHTML=`<h1>${view==='assets'?'Assets':view==='work'?'Work Orders':'Files'}</h1><div class="grid">${list.map(card).join('')||'<div class="card">No records.</div>'}</div>`}
function card(r){if(view==='assets')return`<article class="card"><h3>${esc(r.name)}</h3><p>${esc(r.asset_code)} • ${esc(r.asset_type)}<br>${esc(r.location)} • ${esc(r.status)} • ${esc(r.running_state)}</p><div class="actions"><button onclick="editRecord('${r.id}')">Edit</button><button onclick="removeRecord('${r.id}')">Delete</button></div></article>`;if(view==='work')return`<article class="card"><h3>${esc(r.title)}</h3><p>${esc(r.assets?.name||'General')} • ${esc(r.priority)} • ${esc(r.status)}<br>${esc(r.description)}</p><div class="actions"><button onclick="editRecord('${r.id}')">Edit</button><button onclick="removeRecord('${r.id}')">Delete</button></div></article>`;return`<article class="card"><h3>${esc(r.file_name)}</h3><p>${esc(r.category)} • ${Math.ceil((r.size_bytes||0)/1024)} KB</p><button onclick="downloadFile('${r.object_path}')">Open</button></article>`}
window.editRecord=id=>openRecordForm(records.find(r=>r.id===id));window.removeRecord=async id=>{const table=view==='assets'?'assets':'work_orders',record={id};if(navigator.onLine){const{error}=await sb.from(table).delete().eq('id',id);if(error)return toast(error.message)}else await enqueue({table,action:'delete',record});toast('Delete saved');loadView()};
function field(name,label,value='',type='text'){return`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" required></label>`}
function openRecordForm(r={}){if(view==='files')return $('#fileInput')?.click()||createFileInput();$('#modalTitle').textContent=r.id?'Edit record':`Add ${view==='assets'?'asset':'work order'}`;if(view==='assets')$('#fields').innerHTML=field('asset_code','Asset code',r.asset_code)+field('name','Name',r.name)+field('asset_type','Type',r.asset_type)+field('location','Location',r.location)+field('manufacturer','Manufacturer',r.manufacturer)+field('model','Model',r.model)+field('serial_number','Serial number',r.serial_number)+field('rating','Rating / capacity',r.rating)+field('status','Status',r.status||'operational')+field('running_state','Running state',r.running_state||'shutdown');else $('#fields').innerHTML=field('title','Title',r.title)+`<label>Description<textarea name="description" required>${esc(r.description)}</textarea></label>`+field('priority','Priority',r.priority||'medium')+field('status','Status',r.status||'open')+field('due_at','Due date',r.due_at?.slice(0,16)||'','datetime-local');formHandler=async values=>{const table=view==='assets'?'assets':'work_orders',base={...r};delete base.assets;const record={...base,...values,id:r.id||crypto.randomUUID(),organization_id:org.id,plant_id:plant.id,created_by:r.created_by||userId,updated_at:new Date().toISOString()};if(navigator.onLine){const{error}=await sb.from(table).upsert(record);if(error)throw error}else await enqueue({table,action:'upsert',record});toast('Saved');loadView()};const modal=$('#modal');if(typeof modal.showModal==='function')modal.showModal();else{modal.setAttribute('open','');modal.style.display='block'}}
$('#recordForm').onsubmit=async e=>{e.preventDefault();try{if(!userId){const result=await sb.auth.getUser();userId=result.data.user?.id;if(!userId)throw Error('Your session expired. Please sign in again.')}await formHandler(Object.fromEntries(new FormData(e.target)));if(typeof $('#modal').close==='function')$('#modal').close();else{$('#modal').removeAttribute('open');$('#modal').style.display='none'}}catch(x){console.error('Save failed',x);toast(x.message||String(x))}};
function createFileInput(){const i=document.createElement('input');i.type='file';i.id='fileInput';i.multiple=true;i.hidden=true;i.onchange=()=>uploadFiles(i.files);document.body.append(i);i.click()}
async function uploadFiles(files){for(const file of files){const id=crypto.randomUUID(),path=`${org.id}/${plant.id}/${id}-${file.name.replace(/[^\w.-]/g,'_')}`;const{error}=await sb.storage.from(FILE_BUCKET).upload(path,file);if(error){toast(error.message);continue}await sb.from('file_metadata').insert({id,organization_id:org.id,plant_id:plant.id,bucket:FILE_BUCKET,object_path:path,file_name:file.name,mime_type:file.type,size_bytes:file.size,category:'manual',uploaded_by:userId})}toast('Upload complete');loadView()}
window.downloadFile=async path=>{const{data:d,error}=await sb.storage.from(FILE_BUCKET).createSignedUrl(path,120);if(error)return toast(error.message);open(d.signedUrl,'_blank')};
function subscribe(){channel?.unsubscribe();channel=sb.channel(`plant-${plant.id}`).on('postgres_changes',{event:'*',schema:'public',table:'assets',filter:`plant_id=eq.${plant.id}`},()=>view==='assets'&&loadView()).on('postgres_changes',{event:'*',schema:'public',table:'work_orders',filter:`plant_id=eq.${plant.id}`},()=>view==='work'&&loadView()).subscribe()}
async function flush(){setSync();const n=await flushQueue(sb);if(n)toast(`${n} offline action(s) synchronized`)}window.addEventListener('online',flush);window.addEventListener('offline',setSync);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=4.0.7',{updateViaCache:'none'});init();