// PlantMaster Pro v4.4 operational workflows.
// Uses the existing authenticated Supabase client and workspace context supplied by app.js.
export function createOperations(ctx){
  const {sb,$,esc,toast}=ctx;
  const inputTypes=['yes_no','ok_not_ok','good_bad','normal_abnormal','percentage','temperature','pressure','current','voltage','vibration','running_hours','number','text','notes','date','time'];
  const shifts=['General Shift','Shift A','Shift B','Shift C','Rest / Off'];
  let module='people',tab='members',cache=[],search='';
  const S=()=>ctx.state();
  const owner=()=>S().role==='owner';
  const leader=()=>['owner','manager','supervisor'].includes(S().role);
  const id=()=>crypto.randomUUID();
  const now=()=>new Date().toISOString();
  const value=(fd,k)=>String(fd.get(k)||'').trim();
  const actor=()=>({worker_name:S().profile?.full_name||S().email||'Signed-in worker',designation:S().profile?.designation||S().role,shift_name:S().profile?.default_shift||'General Shift'});
  const stateBadge=v=>`<span class="state ${esc(String(v||'').toLowerCase())}">${esc(v||'—')}</span>`;
  const empty=t=>`<div class="empty-state"><b>No records yet</b><p>${esc(t)}</p></div>`;
  const options=(items,selected='')=>items.map(x=>`<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(x.replaceAll('_',' / '))}</option>`).join('');
  const field=(name,label,type='text',val='',required=true,extra='')=>`<label class="form-field"><span>${esc(label)}${required?' *':''}</span><input name="${name}" type="${type}" value="${esc(val)}" ${required?'required':''} ${extra}></label>`;
  const area=(name,label,val='',required=true)=>`<label class="form-field span-2"><span>${esc(label)}${required?' *':''}</span><textarea name="${name}" ${required?'required':''}>${esc(val)}</textarea></label>`;
  const select=(name,label,items,selected='',required=true)=>`<label class="form-field"><span>${esc(label)}${required?' *':''}</span><select name="${name}" ${required?'required':''}>${options(items,selected)}</select></label>`;

  async function audit(action,entity_type,entity_id,details={}){
    const s=S();
    const payload={organization_id:s.org.id,plant_id:s.plant.id,user_id:s.userId,action,entity_type,entity_id:String(entity_id||''),details:{...details,...actor(),timestamp:now()}};
    const {error}=await sb.from('audit_logs').insert(payload);if(error)console.warn('Audit log:',error.message);
  }
  async function query(q){const r=await q;if(r.error)throw r.error;return r.data||[]}
  async function write(q,success,action,entity,idValue){const r=await q;if(r.error)throw r.error;if(action)await audit(action,entity,idValue);toast(success);return r.data}

  function dialog(title,html,onSubmit,{wide=true,submit='Save'}={}){
    const old=document.querySelector('#opsDialog');if(old)old.remove();
    const d=document.createElement('dialog');d.id='opsDialog';d.className=wide?'wide-dialog':'';
    d.innerHTML=`<form method="dialog" class="ops-form"><div class="dialog-head"><div><small>PlantMaster Operations</small><h2>${esc(title)}</h2></div><button type="button" class="icon-btn" data-close aria-label="Close">✕</button></div><div class="form-grid">${html}</div><div id="opsFormError" class="form-error"></div><menu><button type="button" class="secondary" data-close>Cancel</button><button class="primary" type="submit">${esc(submit)}</button></menu></form>`;
    document.body.append(d);d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());
    d.querySelector('form').onsubmit=async e=>{e.preventDefault();const save=e.submitter;save.disabled=true;save.textContent='Saving…';try{await onSubmit(new FormData(e.target));d.close()}catch(err){d.querySelector('#opsFormError').textContent=err.message||String(err);save.disabled=false;save.textContent=submit}};
    d.addEventListener('close',()=>setTimeout(()=>d.remove(),0));d.showModal();enhanceVoice(d);return d;
  }
  function enhanceVoice(root=document){if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window))return;root.querySelectorAll('input[type=text],input[type=search],textarea').forEach(el=>{if(el.parentElement.querySelector('.voice-btn'))return;const b=document.createElement('button');b.type='button';b.className='voice-btn';b.title='Voice to text';b.textContent='🎙';b.onclick=()=>voiceInto(el);el.insertAdjacentElement('afterend',b)})}
  function voiceInto(el){if(!isSecureContext)return toast('Voice input requires HTTPS');const R=window.SpeechRecognition||window.webkitSpeechRecognition,r=new R();r.lang='en-PK';r.interimResults=false;r.onresult=e=>{el.value+=(el.value?' ':'')+e.results[0][0].transcript;el.dispatchEvent(new Event('input',{bubbles:true}))};r.onerror=e=>toast(`Microphone: ${e.error}`);r.start()}
  function guide(name){const guides={people:['Members: owner can edit role, worker details, permissions, deactivate and recover.','Roster and attendance save to shift_assignments and attendance.','Handovers and logs store worker name, designation, shift and timestamp.','CSV Download saves the current tab to your Downloads folder.'],checklists:['Create a template, then add ordered items with type, unit, limits and required status.','Run opens every checklist item for data entry.','Values save in checklist_runs and checklist_values; limit failures are marked automatically.','Supervisor approval is available to owner, manager and supervisor.'],maintenance:['Plans hold the schedule, due date and assigned asset.','Complete records work done, worker, designation, shift, tools, parts, readings, root cause and downtime.','Completion history is preserved separately from the recurring plan.','Remove moves a plan to Recovery; only owner can restore or permanently erase.'],inventory:['Spares store stock and reorder level. Receive/Issue creates an inventory transaction.','Tool checkout, return, inspection and calibration create immutable transaction history.','Every transaction records worker identity and timestamp.','Removed records remain recoverable by the owner.']};dialog(`${name[0].toUpperCase()+name.slice(1)} Guide`,`<div class="guide-steps span-2">${(guides[name]||[]).map((x,i)=>`<div><b>${i+1}</b><p>${esc(x)}</p></div>`).join('')}</div>`,async()=>{}, {submit:'Close'});const d=$('#opsDialog');d.querySelector('form').onsubmit=e=>{e.preventDefault();d.close()}}

  function toolbar(title,addLabel='Add'){
    const t=$('#toolbar');t.hidden=false;t.innerHTML=`<div class="module-toolbar"><div><small>Operations</small><b>${esc(title)}</b></div><div class="toolbar-actions"><div class="search-wrap"><span>⌕</span><input id="opsSearch" type="search" placeholder="Search ${esc(title.toLowerCase())}…" value="${esc(search)}"></div><button id="opsGuide" class="secondary">? Guide</button>${addLabel?`<button id="opsAdd" class="primary">＋ ${esc(addLabel)}</button>`:''}</div></div>`;
    $('#opsSearch').oninput=e=>{search=e.target.value.toLowerCase();paint()};$('#opsGuide').onclick=()=>guide(module);enhanceVoice(t);
  }
  function tabs(items){return`<div class="tabs">${items.map(([key,label])=>`<button class="${tab===key?'active':''}" data-tab="${key}">${label}</button>`).join('')}</div>`}
  function bindTabs(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;search='';render(module)})}
  function matches(x){return !search||JSON.stringify(x).toLowerCase().includes(search)}
  function paint(){if(module==='people')paintPeople();if(module==='checklists')paintChecklists();if(module==='maintenance')paintMaintenance();if(module==='inventory')paintInventory()}

  async function render(next){module=next;try{if(next==='people')await loadPeople();if(next==='checklists')await loadChecklists();if(next==='maintenance')await loadMaintenance();if(next==='inventory')await loadInventory();if(next==='recovery')await loadRecovery()}catch(e){$('#content').innerHTML=`<div class="error-state"><h2>Could not load ${esc(next)}</h2><p>${esc(e.message)}</p><button onclick="location.reload()">Retry</button></div>`}}

  async function loadPeople(){toolbar('Roster & Attendance','Add record');
    if(tab==='members'){const members=await query(sb.from('organization_members').select('user_id,role,active,permissions,deactivated_at,created_at').eq('organization_id',S().org.id));const ids=members.map(x=>x.user_id);const profiles=ids.length?await query(sb.from('profiles').select('id,full_name,employee_id,designation,skills,contact,default_shift').in('id',ids)):[];const pending=owner()?await query(sb.from('invitations').select('*').eq('organization_id',S().org.id).is('accepted_at',null).order('created_at',{ascending:false})):[];cache=[...members.map(m=>({...m,profile:profiles.find(p=>p.id===m.user_id)})),...pending.map(i=>({...i,_pending:true,profile:i.worker_details||{}}))]}
    if(tab==='roster')cache=await query(sb.from('shift_assignments').select('*').eq('plant_id',S().plant.id).order('work_date',{ascending:false}).limit(150));
    if(tab==='attendance')cache=await query(sb.from('attendance').select('*').eq('plant_id',S().plant.id).order('work_date',{ascending:false}).limit(150));
    if(tab==='handovers')cache=await query(sb.from('shift_handovers').select('*').eq('plant_id',S().plant.id).order('created_at',{ascending:false}).limit(150));
    if(tab==='logs')cache=await query(sb.from('daily_logs').select('*').eq('plant_id',S().plant.id).order('created_at',{ascending:false}).limit(150));
    $('#opsAdd').textContent=tab==='members'?'＋ Add Worker':tab==='roster'?'＋ Assign Shift':tab==='attendance'?'＋ Attendance':tab==='handovers'?'＋ Handover':'＋ Daily Log';$('#opsAdd').onclick=peopleAdd;paintPeople();
  }
  function paintPeople(){const titles={members:'Members',roster:'Duty Roster',attendance:'Attendance',handovers:'Shift Handovers',logs:'Daily Logs'};$('#content').innerHTML=`<section class="module-head"><div><h1>People</h1><p>Worker records, shifts, attendance and operational handovers</p></div><div class="export-mini"><button onclick="PMOps.exportPeople('csv')">CSV</button><button onclick="PMOps.exportPeople('excel')">Excel</button><button onclick="PMOps.exportPeople('word')">Word</button><button onclick="PMOps.exportPeople('pdf')">PDF</button></div></section>${tabs([['members','Members'],['roster','Roster'],['attendance','Attendance'],['handovers','Handovers'],['logs','Daily Logs']])}<h2 class="section-title">${titles[tab]}</h2><div class="record-grid">${cache.filter(matches).map(peopleCard).join('')||empty('Use Add record to create the first entry.')}</div>`;bindTabs()}
  function peopleCard(x){if(tab==='members'&&x._pending){const p=x.profile||{};return`<article class="record-card pending-card"><div class="record-title"><div class="avatar">${esc((p.full_name||x.email||'?')[0])}</div><div><h3>${esc(p.full_name||x.email||'Pending worker')}</h3><p>${esc(p.employee_id||'No employee ID')} • ${esc(p.designation||x.role)}</p></div><span class="state warning">Pending</span></div><dl><div><dt>Email</dt><dd>${esc(x.email||'QR invitation')}</dd></div><div><dt>Shift</dt><dd>${esc(p.default_shift||'General Shift')}</dd></div><div><dt>Role</dt><dd>${esc(x.role)}</dd></div><div><dt>Expires</dt><dd>${new Date(x.expires_at).toLocaleDateString()}</dd></div></dl><div class="invite-actions"><button class="email-btn" onclick="PMOps.emailWorker('${x.id}')">✉ Email</button><button class="whatsapp-btn" onclick="PMOps.whatsappWorker('${x.id}')">◉ WhatsApp</button><button onclick="PMOps.shareWorker('${x.id}')">⧉ Copy / Share</button><button class="danger" onclick="PMOps.cancelWorker('${x.id}')">Cancel</button></div></article>`}if(tab==='members'){const p=x.profile||{};return`<article class="record-card ${!x.active?'muted':''}"><div class="record-title"><div class="avatar">${esc((p.full_name||'?')[0])}</div><div><h3>${esc(p.full_name||x.user_id)}</h3><p>${esc(p.employee_id||'No employee ID')} • ${esc(p.designation||x.role)}</p></div>${stateBadge(x.active?'Active':'Inactive')}</div><dl><div><dt>Role</dt><dd>${esc(x.role)}</dd></div><div><dt>Shift</dt><dd>${esc(p.default_shift||'—')}</dd></div><div><dt>Skills</dt><dd>${esc((p.skills||[]).join(', ')||'—')}</dd></div><div><dt>Contact</dt><dd>${esc(p.contact||'—')}</dd></div></dl><div class="actions">${owner()?`<button onclick="PMOps.editMember('${x.user_id}')">Edit & Permissions</button>${x.active&&x.role!=='owner'?`<button onclick="PMOps.transferOwnership('${x.user_id}')">Transfer Ownership</button>`:''}<button class="${x.active?'danger':'success'}" onclick="PMOps.toggleMember('${x.user_id}',${x.active})">${x.active?'Deactivate':'Recover'}</button>`:''}</div></article>`}
    if(tab==='roster')return basicCard(x.work_date,x.shift_name,`Worker: ${x.user_id}`,x.status);
    if(tab==='attendance')return basicCard(x.work_date,`${x.status} • ${x.shift_name||''}`,`${x.check_in?'In '+new Date(x.check_in).toLocaleTimeString():''} ${x.check_out?'Out '+new Date(x.check_out).toLocaleTimeString():''}`,x.status);
    if(tab==='handovers')return basicCard(`${x.from_shift} → ${x.to_shift}`,x.summary,`${x.worker_name} • ${x.designation||'—'} • ${new Date(x.created_at).toLocaleString()}`,'handover');
    return basicCard(`${x.log_date} • ${x.shift_name}`,x.entry,`${x.category} • ${x.worker_name} • ${x.designation||'—'}`,'log')}
  function basicCard(title,body,meta,status){return`<article class="record-card"><div class="record-title"><div><h3>${esc(title)}</h3><p>${esc(meta)}</p></div>${stateBadge(status)}</div><p>${esc(body)}</p></article>`}
  async function peopleAdd(){if(tab==='members')return inviteWorker();if(tab==='roster')return rosterForm();if(tab==='attendance')return attendanceForm();if(tab==='handovers')return handoverForm();return dailyLogForm()}
  function inviteWorker(){if(!owner())return toast('Only the owner can add workers');dialog('Add worker',field('email','Work email','email')+select('role','Role',['manager','engineer','supervisor','technician','store','viewer'],'technician')+field('full_name','Worker name')+field('employee_id','Employee ID')+field('designation','Designation')+select('default_shift','Default shift',shifts,'General Shift')+field('contact','WhatsApp / contact number','tel','',false)+field('skills','Skills (comma separated)','text','',false)+select('delivery_method','After adding, send invitation by',['save_only','email','whatsapp'],'save_only'),async fd=>{const s=S(),worker_details={full_name:value(fd,'full_name'),employee_id:value(fd,'employee_id'),designation:value(fd,'designation'),default_shift:value(fd,'default_shift'),contact:value(fd,'contact'),skills:value(fd,'skills').split(',').map(v=>v.trim()).filter(Boolean)},payload={organization_id:s.org.id,plant_id:s.plant.id,email:value(fd,'email'),role:value(fd,'role'),worker_details,created_by:s.userId};const r=await sb.from('invitations').insert(payload).select().single();if(r.error)throw r.error;await audit('worker_invited','invitation',r.data.id,{email:payload.email,role:payload.role,worker_details});toast('Worker added as Pending');const delivery=value(fd,'delivery_method');await loadPeople();setTimeout(()=>{if(delivery==='email')window.PMOps.emailWorker(r.data.id);if(delivery==='whatsapp')window.PMOps.whatsappWorker(r.data.id)},150)}, {submit:'Add Worker'})}
  window.PMOps=window.PMOps||{};
  function workerInvite(inviteId){const x=cache.find(v=>v.id===inviteId&&v._pending);if(!x)return null;const p=x.profile||{},link=`${location.origin}${location.pathname}?invite=${x.token}`,text=`PlantMaster worker account\nCompany: ${S().org.name}\nWorker: ${p.full_name||x.email||''}\nRole: ${x.role}\nOpen this secure link to create/sign in to your account:\n${link}`;return{x,p,link,text}}
  window.PMOps.shareWorker=inviteId=>{const i=workerInvite(inviteId);if(!i)return toast('Invitation not found');navigator.share?navigator.share({title:'PlantMaster worker account',text:i.text,url:i.link}):navigator.clipboard.writeText(i.link).then(()=>toast('Worker account link copied'))};
  window.PMOps.emailWorker=inviteId=>{const i=workerInvite(inviteId);if(!i)return toast('Invitation not found');if(!i.x.email)return toast('Add an email address for this worker');location.href=`mailto:${encodeURIComponent(i.x.email)}?subject=${encodeURIComponent(`Join ${S().org.name} on PlantMaster`)}&body=${encodeURIComponent(i.text)}`};
  window.PMOps.whatsappWorker=inviteId=>{const i=workerInvite(inviteId);if(!i)return toast('Invitation not found');let phone=String(i.p.contact||'').replace(/\D/g,'');if(!phone)phone=String(prompt('Worker WhatsApp number with country code, for example 923001234567:')||'').replace(/\D/g,'');if(!phone)return;location.href=`https://wa.me/${phone}?text=${encodeURIComponent(i.text)}`};
  window.PMOps.cancelWorker=async inviteId=>{if(!owner()||!confirm('Cancel this pending worker invitation?'))return;const r=await sb.from('invitations').delete().eq('id',inviteId);if(r.error)return toast(r.error.message);await audit('worker_invitation_cancelled','invitation',inviteId);toast('Pending worker cancelled');await loadPeople()};
  window.PMOps.editMember=uid=>{const x=cache.find(y=>y.user_id===uid),p=x.profile||{};const permissionNames=['assets.add','assets.edit','work.add','work.complete','checklists.run','maintenance.complete','inventory.transact','support.reply','reports.download'];dialog('Worker details & permissions',field('full_name','Worker name','text',p.full_name)+field('employee_id','Employee ID','text',p.employee_id||'',false)+field('designation','Designation','text',p.designation||'',false)+select('default_shift','Default shift',shifts,p.default_shift||'General Shift')+field('contact','Contact','tel',p.contact||'',false)+field('skills','Skills (comma separated)','text',(p.skills||[]).join(', '),false)+select('role','Workspace role',['owner','manager','engineer','supervisor','technician','store','viewer'],x.role)+`<fieldset class="span-2 permission-grid"><legend>Granted actions</legend>${permissionNames.map(n=>`<label><input type="checkbox" name="permission" value="${n}" ${x.permissions?.[n]?'checked':''}> ${n.replace('.',' — ')}</label>`).join('')}</fieldset>`,async fd=>{const profile={full_name:value(fd,'full_name'),employee_id:value(fd,'employee_id')||null,designation:value(fd,'designation')||null,default_shift:value(fd,'default_shift'),contact:value(fd,'contact')||null,skills:value(fd,'skills').split(',').map(v=>v.trim()).filter(Boolean),updated_at:now()};let r=await sb.from('profiles').update(profile).eq('id',uid);if(r.error)throw r.error;const permissions={};fd.getAll('permission').forEach(k=>permissions[k]=true);r=await sb.from('organization_members').update({role:value(fd,'role'),permissions,updated_at:now()}).eq('organization_id',S().org.id).eq('user_id',uid);if(r.error)throw r.error;await audit('worker_updated','profile',uid,{role:value(fd,'role'),permissions});toast('Worker updated');await loadPeople()})};
  window.PMOps.transferOwnership=async uid=>{if(!owner())return toast('Owner access required');const worker=cache.find(x=>x.user_id===uid),name=worker?.profile?.full_name||uid;if(prompt(`Transfer company ownership to ${name}? Your role will become manager. Type TRANSFER:`)!=='TRANSFER')return;const r=await sb.rpc('transfer_organization_ownership',{p_organization_id:S().org.id,p_new_owner:uid});if(r.error)return toast(r.error.message);toast('Ownership transferred. Reloading permissions…');setTimeout(()=>location.reload(),800)};
  window.PMOps.toggleMember=async(uid,active)=>{if(!owner())return toast('Owner permission required');if(!confirm(`${active?'Deactivate':'Recover'} this worker?`))return;try{await write(sb.from('organization_members').update({active:!active,deactivated_at:active?now():null,updated_at:now()}).eq('organization_id',S().org.id).eq('user_id',uid),'Worker status updated',active?'worker_deactivated':'worker_recovered','member',uid);await loadPeople()}catch(e){toast(e.message)}};
  async function memberChoices(){return cache.filter(x=>x.active).map(x=>[x.user_id,x.profile?.full_name||x.user_id])}
  function userSelect(name,label,list){return`<label class="form-field"><span>${label} *</span><select name="${name}" required>${list.map(([v,l])=>`<option value="${v}">${esc(l)}</option>`).join('')}</select></label>`}
  async function rosterForm(){const members=tab==='members'?cache:(await (async()=>{const m=await query(sb.from('organization_members').select('user_id,active').eq('organization_id',S().org.id).eq('active',true));const ids=m.map(x=>x.user_id),p=ids.length?await query(sb.from('profiles').select('id,full_name').in('id',ids)):[];return m.map(x=>({...x,profile:p.find(y=>y.id===x.user_id)}))})());const choices=members.map(x=>[x.user_id,x.profile?.full_name||x.user_id]);dialog('Assign duty shift',userSelect('user_id','Worker',choices)+field('work_date','Work date','date',new Date().toISOString().slice(0,10))+select('shift_name','Shift',shifts,'Shift A')+select('status','Status',['scheduled','confirmed','rest'],'scheduled'),async fd=>{const rec={id:id(),organization_id:S().org.id,plant_id:S().plant.id,user_id:value(fd,'user_id'),work_date:value(fd,'work_date'),shift_name:value(fd,'shift_name'),status:value(fd,'status'),created_by:S().userId};const r=await sb.from('shift_assignments').upsert(rec,{onConflict:'plant_id,user_id,work_date'});if(r.error)throw r.error;await audit('shift_assigned','shift_assignment',rec.id,rec);toast('Shift assigned');await loadPeople()})}
  function attendanceForm(){dialog('Record attendance',field('user_id','Worker user ID')+field('work_date','Work date','date',new Date().toISOString().slice(0,10))+select('shift_name','Shift',shifts,'Shift A')+select('status','Attendance',['present','absent','leave','late','half-day'],'present')+field('check_in','Check in','datetime-local','',false)+field('check_out','Check out','datetime-local','',false)+area('notes','Notes','',false),async fd=>{const rec={id:id(),organization_id:S().org.id,plant_id:S().plant.id,user_id:value(fd,'user_id'),work_date:value(fd,'work_date'),shift_name:value(fd,'shift_name'),status:value(fd,'status'),check_in:value(fd,'check_in')||null,check_out:value(fd,'check_out')||null,notes:value(fd,'notes')||null,created_by:S().userId,updated_at:now()};const r=await sb.from('attendance').upsert(rec,{onConflict:'plant_id,user_id,work_date'});if(r.error)throw r.error;await audit('attendance_recorded','attendance',rec.id,{status:rec.status,shift_name:rec.shift_name});toast('Attendance saved');await loadPeople()})}
  function handoverForm(){dialog('Shift handover',field('work_date','Work date','date',new Date().toISOString().slice(0,10))+select('from_shift','From shift',shifts,'Shift A')+select('to_shift','To shift',shifts,'Shift B')+area('summary','Handover summary')+area('pending_work','Pending work','',false)+area('safety_notes','Safety notes','',false),async fd=>{const rec={id:id(),organization_id:S().org.id,plant_id:S().plant.id,work_date:value(fd,'work_date'),from_shift:value(fd,'from_shift'),to_shift:value(fd,'to_shift'),summary:value(fd,'summary'),pending_work:value(fd,'pending_work')||null,safety_notes:value(fd,'safety_notes')||null,created_by:S().userId,...actor()};delete rec.shift_name;await write(sb.from('shift_handovers').insert(rec),'Handover saved','handover_created','shift_handover',rec.id);await loadPeople()})}
  function dailyLogForm(){dialog('Daily operational log',field('log_date','Log date','date',new Date().toISOString().slice(0,10))+select('shift_name','Shift',shifts,actor().shift_name)+select('category','Category',['operations','maintenance','safety','quality','production'],'operations')+area('entry','Log entry'),async fd=>{const rec={id:id(),organization_id:S().org.id,plant_id:S().plant.id,log_date:value(fd,'log_date'),shift_name:value(fd,'shift_name'),category:value(fd,'category'),entry:value(fd,'entry'),created_by:S().userId,worker_name:actor().worker_name,designation:actor().designation};await write(sb.from('daily_logs').insert(rec),'Daily log saved','daily_log_created','daily_log',rec.id);await loadPeople()})}

  async function loadChecklists(){toolbar('Checklists','New Template');cache=await query(sb.from('checklist_templates').select('*,assets(name),checklist_items(*)').eq('plant_id',S().plant.id).is('removed_at',null).order('updated_at',{ascending:false}));$('#opsAdd').onclick=()=>templateForm();paintChecklists()}
  function paintChecklists(){$('#content').innerHTML=`<section class="module-head"><div><h1>Checklists</h1><p>Build templates, capture readings and approve completed rounds</p></div><button class="secondary" id="checkRunLog">Run Log</button></section><div class="record-grid">${cache.filter(matches).map(x=>`<article class="record-card"><div class="record-title"><div><h3>${esc(x.name)}</h3><p>${esc(x.assets?.name||'General')} • ${esc(x.schedule||'On demand')} • ${esc(x.shift_name||'All shifts')}</p></div>${stateBadge(x.active?'Active':'Inactive')}</div><p>${x.checklist_items?.length||0} inspection items</p><div class="actions"><button class="primary" onclick="PMOps.runChecklist('${x.id}')">▶ Run</button><button onclick="PMOps.editChecklist('${x.id}')">Edit Items</button>${owner()?`<button class="danger" onclick="PMOps.remove('checklist_templates','${x.id}')">Remove</button>`:''}</div></article>`).join('')||empty('Create a checklist template and add inspection items.')}</div>`;$('#checkRunLog').onclick=checklistRuns}
  function templateForm(x={}){dialog(x.id?'Edit checklist':'New checklist',field('name','Checklist name','text',x.name||'')+field('schedule','Schedule','text',x.schedule||'Daily',false)+select('shift_name','Shift',shifts,x.shift_name||'General Shift')+area('instructions','Instructions',x.instructions||'',false),async fd=>{const rec={...x,id:x.id||id(),organization_id:S().org.id,plant_id:S().plant.id,name:value(fd,'name'),schedule:value(fd,'schedule'),shift_name:value(fd,'shift_name'),instructions:value(fd,'instructions'),active:true,created_by:x.created_by||S().userId,updated_at:now()};const r=await sb.from('checklist_templates').upsert(rec);if(r.error)throw r.error;await audit(x.id?'checklist_updated':'checklist_created','checklist_template',rec.id,{name:rec.name});toast('Checklist saved');await loadChecklists();if(!x.id)window.PMOps.editChecklist(rec.id)})}
  window.PMOps.editChecklist=tid=>{const x=cache.find(y=>y.id===tid);dialog(`Checklist items — ${x.name}`,`<div class="span-2 item-builder"><div id="builderRows">${(x.checklist_items||[]).sort((a,b)=>a.sort_order-b.sort_order).map(itemRow).join('')}</div><button type="button" id="addBuilderRow">＋ Add item</button></div>`,async fd=>{const old=x.checklist_items||[];const labels=fd.getAll('item_label'),types=fd.getAll('item_type'),units=fd.getAll('item_unit'),mins=fd.getAll('item_min'),maxs=fd.getAll('item_max'),required=fd.getAll('item_required');const rows=labels.map((label,i)=>({id:old[i]?.id||id(),template_id:tid,sort_order:i+1,label:label.trim(),input_type:types[i],unit:units[i]||null,required:required.includes(String(i)),limits:{min:mins[i]===''?null:Number(mins[i]),max:maxs[i]===''?null:Number(maxs[i])}})).filter(r=>r.label);const del=old.filter(o=>!rows.some(r=>r.id===o.id)).map(o=>o.id);if(del.length){const q=await sb.from('checklist_items').delete().in('id',del);if(q.error)throw q.error}if(rows.length){const q=await sb.from('checklist_items').upsert(rows);if(q.error)throw q.error}await audit('checklist_items_updated','checklist_template',tid,{item_count:rows.length});toast('Checklist items saved');await loadChecklists()});const rows=$('#builderRows');$('#addBuilderRow').onclick=()=>{const index=rows.children.length;rows.insertAdjacentHTML('beforeend',itemRow({sort_order:index+1},index))};enhanceVoice($('#opsDialog'))};
  function itemRow(x={},index=null){const i=index??Math.max(0,(x.sort_order||1)-1),lim=x.limits||{};return`<div class="builder-row"><span class="drag">${i+1}</span><input name="item_label" placeholder="Inspection item" value="${esc(x.label||'')}" required><select name="item_type">${options(inputTypes,x.input_type||'ok_not_ok')}</select><input name="item_unit" placeholder="Unit" value="${esc(x.unit||'')}"><input name="item_min" type="number" step="any" placeholder="Min" value="${esc(lim.min??'')}"><input name="item_max" type="number" step="any" placeholder="Max" value="${esc(lim.max??'')}"><label class="required-check"><input name="item_required" type="checkbox" value="${i}" ${x.required!==false?'checked':''}> Required</label><button type="button" class="danger" onclick="this.closest('.builder-row').remove()">✕</button></div>`}
  window.PMOps.runChecklist=tid=>{const t=cache.find(x=>x.id===tid),items=(t.checklist_items||[]).sort((a,b)=>a.sort_order-b.sort_order);if(!items.length)return toast('Add checklist items before running it');dialog(`Run — ${t.name}`,`${select('shift_name','Shift',shifts,actor().shift_name)}${area('notes','Work done / notes','',false)}<div class="span-2 run-items">${items.map(runItem).join('')}</div>`,async fd=>{const run={id:id(),organization_id:S().org.id,plant_id:S().plant.id,template_id:tid,asset_id:t.asset_id||null,performed_by:S().userId,shift_name:value(fd,'shift_name'),designation:actor().designation,status:'completed',notes:value(fd,'notes')||null,performed_at:now(),completed_at:now()};let q=await sb.from('checklist_runs').insert(run);if(q.error)throw q.error;const vals=items.map(item=>{const raw=value(fd,`item_${item.id}`),n=Number(raw),numeric=raw!==''&&!Number.isNaN(n),min=item.limits?.min,max=item.limits?.max;const failed=(numeric&&min!=null&&n<Number(min))||(numeric&&max!=null&&n>Number(max))||['no','not ok','bad','abnormal'].includes(raw.toLowerCase());return{id:id(),run_id:run.id,item_id:item.id,value:{raw},failed,note:value(fd,`note_${item.id}`)||null}});q=await sb.from('checklist_values').insert(vals);if(q.error)throw q.error;const failures=vals.filter(v=>v.failed).length;if(failures)await sb.from('notifications').insert({organization_id:S().org.id,plant_id:S().plant.id,title:`Checklist alarm: ${t.name}`,body:`${failures} item(s) failed limits. Completed by ${actor().worker_name}.`});await audit('checklist_completed','checklist_run',run.id,{template:t.name,failures,shift_name:run.shift_name});toast(failures?`Completed with ${failures} alarm(s)`:'Checklist completed');await loadChecklists()}, {submit:'Complete Checklist'})};
  function runItem(item){const type=item.input_type,choices={yes_no:['Yes','No'],ok_not_ok:['OK','Not OK'],good_bad:['Good','Bad'],normal_abnormal:['Normal','Abnormal']}[type];let control;if(choices)control=`<select name="item_${item.id}" ${item.required?'required':''}><option value="">Select…</option>${options(choices)}</select>`;else if(type==='notes'||type==='text')control=`<textarea name="item_${item.id}" ${item.required?'required':''}></textarea>`;else control=`<input name="item_${item.id}" type="${['date','time'].includes(type)?type:'number'}" ${['number','percentage','temperature','pressure','current','voltage','vibration','running_hours'].includes(type)?'step="any"':''} ${item.required?'required':''}>`;return`<div class="run-item"><div><b>${esc(item.label)}</b><small>${esc(item.unit||'')} ${item.limits?.min!=null?`Min ${esc(item.limits.min)}`:''} ${item.limits?.max!=null?`Max ${esc(item.limits.max)}`:''}</small></div>${control}<input name="note_${item.id}" placeholder="Item note (optional)"></div>`}
  async function checklistRuns(){try{const runs=await query(sb.from('checklist_runs').select('*,checklist_templates(name)').eq('plant_id',S().plant.id).order('performed_at',{ascending:false}).limit(100));dialog('Checklist run log',`<div class="span-2 table-wrap"><table><thead><tr><th>Date</th><th>Checklist</th><th>Shift</th><th>Status</th><th>Approval</th></tr></thead><tbody>${runs.map(r=>`<tr><td>${new Date(r.performed_at).toLocaleString()}</td><td>${esc(r.checklist_templates?.name)}</td><td>${esc(r.shift_name)}</td><td>${esc(r.status)}</td><td>${r.supervisor_approved_at?'Approved':leader()?`<button type="button" onclick="PMOps.approveRun('${r.id}')">Approve</button>`:'Pending'}</td></tr>`).join('')}</tbody></table></div>`,async()=>{}, {submit:'Close'});const d=$('#opsDialog');d.querySelector('form').onsubmit=e=>{e.preventDefault();d.close()}}catch(e){toast(e.message)}}
  window.PMOps.approveRun=async rid=>{try{await write(sb.from('checklist_runs').update({supervisor_approved_by:S().userId,supervisor_approved_at:now()}).eq('id',rid),'Checklist approved','checklist_approved','checklist_run',rid);$('#opsDialog')?.close()}catch(e){toast(e.message)}};

  async function loadMaintenance(){toolbar('Maintenance','New Plan');cache=await query(sb.from('maintenance_plans').select('*,assets(name)').eq('plant_id',S().plant.id).is('removed_at',null).order('next_due'));$('#opsAdd').onclick=()=>maintenanceForm();paintMaintenance()}
  function paintMaintenance(){$('#content').innerHTML=`<section class="module-head"><div><h1>Maintenance</h1><p>Preventive plans with attributed completion history</p></div><button class="secondary" id="maintenanceHistory">Completion History</button></section><div class="record-grid">${cache.filter(matches).map(x=>`<article class="record-card"><div class="record-title"><div><h3>${esc(x.title)}</h3><p>${esc(x.assets?.name||'General')} • ${esc(x.frequency)}</p></div>${stateBadge(x.status)}</div><dl><div><dt>Priority</dt><dd>${esc(x.priority)}</dd></div><div><dt>Next due</dt><dd>${esc(x.next_due||'—')}</dd></div><div><dt>Last done</dt><dd>${x.last_completed_at?new Date(x.last_completed_at).toLocaleString():'—'}</dd></div></dl><p>${esc(x.description)}</p><div class="actions"><button class="primary" onclick="PMOps.completeMaintenance('${x.id}')">✓ Work Done</button><button onclick="PMOps.editMaintenance('${x.id}')">Edit</button>${owner()?`<button class="danger" onclick="PMOps.remove('maintenance_plans','${x.id}')">Remove</button>`:''}</div></article>`).join('')||empty('Create preventive or corrective maintenance plans.')}</div>`;$('#maintenanceHistory').onclick=maintenanceHistory}
  function maintenanceForm(x={}){dialog(x.id?'Edit maintenance plan':'New maintenance plan',field('title','Title','text',x.title||'')+field('frequency','Frequency','text',x.frequency||'Monthly')+select('priority','Priority',['low','medium','high','critical'],x.priority||'medium')+field('next_due','Next due','date',x.next_due||'',false)+area('description','Description',x.description||''),async fd=>{const rec={...x,id:x.id||id(),organization_id:S().org.id,plant_id:S().plant.id,title:value(fd,'title'),frequency:value(fd,'frequency'),priority:value(fd,'priority'),next_due:value(fd,'next_due')||null,description:value(fd,'description'),status:x.status||'pending',created_by:x.created_by||S().userId,updated_at:now()};delete rec.assets;const q=await sb.from('maintenance_plans').upsert(rec);if(q.error)throw q.error;await audit(x.id?'maintenance_plan_updated':'maintenance_plan_created','maintenance_plan',rec.id,{title:rec.title});toast('Maintenance plan saved');await loadMaintenance()})}
  window.PMOps.editMaintenance=mid=>maintenanceForm(cache.find(x=>x.id===mid));
  window.PMOps.completeMaintenance=mid=>{const p=cache.find(x=>x.id===mid);dialog(`Complete — ${p.title}`,select('shift_name','Shift',shifts,actor().shift_name)+field('downtime_minutes','Downtime (minutes)','number','0',false,'min="0"')+area('work_done','Work done')+area('tools_used','Tools used','',false)+area('parts_used','Parts used','',false)+area('measurements','Measurements / readings','',false)+area('root_cause','Root cause','',false)+area('corrective_action','Corrective action','',false),async fd=>{const rec={id:id(),organization_id:S().org.id,plant_id:S().plant.id,plan_id:mid,work_done:value(fd,'work_done'),worker_id:S().userId,...actor(),shift_name:value(fd,'shift_name'),tools_used:value(fd,'tools_used')||null,parts_used:value(fd,'parts_used')||null,measurements:{text:value(fd,'measurements')},root_cause:value(fd,'root_cause')||null,corrective_action:value(fd,'corrective_action')||null,downtime_minutes:Number(value(fd,'downtime_minutes'))||0,completed_at:now()};let q=await sb.from('maintenance_completions').insert(rec);if(q.error)throw q.error;q=await sb.from('maintenance_plans').update({status:'completed',last_completed_at:rec.completed_at,last_completed_by:S().userId,updated_at:now()}).eq('id',mid);if(q.error)throw q.error;await audit('maintenance_completed','maintenance_completion',rec.id,{plan_id:mid,title:p.title,shift_name:rec.shift_name,downtime_minutes:rec.downtime_minutes});toast('Maintenance completion recorded');await loadMaintenance()}, {submit:'Record Work Done'})};
  async function maintenanceHistory(){try{const rows=await query(sb.from('maintenance_completions').select('*,maintenance_plans(title)').eq('plant_id',S().plant.id).order('completed_at',{ascending:false}).limit(100));dialog('Maintenance completion history',`<div class="span-2 table-wrap"><table><thead><tr><th>Date</th><th>Plan</th><th>Worker</th><th>Shift</th><th>Work done</th><th>Downtime</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${new Date(r.completed_at).toLocaleString()}</td><td>${esc(r.maintenance_plans?.title)}</td><td>${esc(r.worker_name)}<small>${esc(r.designation||'')}</small></td><td>${esc(r.shift_name)}</td><td>${esc(r.work_done)}</td><td>${r.downtime_minutes||0} min</td></tr>`).join('')}</tbody></table></div>`,async()=>{}, {submit:'Close'});const d=$('#opsDialog');d.querySelector('form').onsubmit=e=>{e.preventDefault();d.close()}}catch(e){toast(e.message)}}

  async function loadInventory(){toolbar('Spares & Tools','Add Item');const [a,b]=await Promise.all([query(sb.from('spares').select('*').eq('plant_id',S().plant.id).is('removed_at',null)),query(sb.from('tools').select('*').eq('plant_id',S().plant.id).is('removed_at',null))]);cache=[...a.map(x=>({...x,_kind:'spare'})),...b.map(x=>({...x,_kind:'tool'}))];$('#opsAdd').onclick=inventoryAdd;paintInventory()}
  function paintInventory(){$('#content').innerHTML=`<section class="module-head"><div><h1>Spares & Tools</h1><p>Stock movements, custody and calibration records</p></div><button class="secondary" id="inventoryHistory">Transaction History</button></section><div class="record-grid">${cache.filter(matches).map(x=>x._kind==='spare'?`<article class="record-card"><div class="record-title"><div><h3>${esc(x.description)}</h3><p>${esc(x.part_number||'No part number')} • ${esc(x.bin_location||'No bin')}</p></div>${stateBadge(Number(x.stock)<=Number(x.min_stock)?'Low stock':'In stock')}</div><dl><div><dt>Stock</dt><dd>${x.stock} ${esc(x.unit||'')}</dd></div><div><dt>Minimum</dt><dd>${x.min_stock}</dd></div><div><dt>Supplier</dt><dd>${esc(x.supplier||'—')}</dd></div></dl><div class="actions"><button class="primary" onclick="PMOps.spareTransaction('${x.id}')">Receive / Issue</button>${owner()?`<button class="danger" onclick="PMOps.remove('spares','${x.id}')">Remove</button>`:''}</div></article>`:`<article class="record-card"><div class="record-title"><div><h3>${esc(x.name)}</h3><p>${esc(x.tool_code||'No code')} • ${esc(x.specification||'')}</p></div>${stateBadge(x.status)}</div><dl><div><dt>Condition</dt><dd>${esc(x.condition||'—')}</dd></div><div><dt>Calibration due</dt><dd>${esc(x.calibration_due||'—')}</dd></div></dl><div class="actions"><button class="primary" onclick="PMOps.toolTransaction('${x.id}')">Checkout / Return</button>${owner()?`<button class="danger" onclick="PMOps.remove('tools','${x.id}')">Remove</button>`:''}</div></article>`).join('')||empty('Add spare parts or tools to begin tracking.')}</div>`;$('#inventoryHistory').onclick=inventoryHistory}
  function inventoryAdd(){dialog('Add inventory item',select('kind','Item type',['spare','tool'],'spare')+field('code','Part / tool code','text','',false)+field('name','Description / name')+field('stock','Opening stock','number','0',false,'step="any"')+field('minimum','Minimum stock','number','0',false,'step="any"')+field('unit','Unit','text','pcs',false)+field('location','Bin / location','text','',false)+field('specification','Specification','text','',false)+field('calibration_due','Calibration due','date','',false),async fd=>{const kind=value(fd,'kind'),rec={id:id(),organization_id:S().org.id,plant_id:S().plant.id,updated_at:now()};if(kind==='spare')Object.assign(rec,{part_number:value(fd,'code')||null,description:value(fd,'name'),stock:Number(value(fd,'stock'))||0,min_stock:Number(value(fd,'minimum'))||0,unit:value(fd,'unit')||null,bin_location:value(fd,'location')||null});else Object.assign(rec,{tool_code:value(fd,'code')||null,name:value(fd,'name'),specification:value(fd,'specification')||null,condition:'good',calibration_due:value(fd,'calibration_due')||null,status:'available'});const q=await sb.from(kind==='spare'?'spares':'tools').insert(rec);if(q.error)throw q.error;await audit(`${kind}_created`,kind,rec.id,{name:value(fd,'name')});toast(`${kind} added`);await loadInventory()})}
  window.PMOps.spareTransaction=sid=>{const x=cache.find(y=>y.id===sid);dialog(`Stock transaction — ${x.description}`,select('transaction_type','Transaction',['receive','issue','adjustment'],'receive')+field('quantity','Quantity','number','1',true,'step="any" min="0.001"')+field('reference','Reference / work order','text','',false)+select('shift_name','Shift',shifts,actor().shift_name),async fd=>{const type=value(fd,'transaction_type'),qty=Number(value(fd,'quantity'));const q=await sb.rpc('transact_spare',{p_spare_id:sid,p_type:type,p_quantity:qty,p_reference:value(fd,'reference')||null,p_worker_name:actor().worker_name,p_designation:actor().designation,p_shift_name:value(fd,'shift_name')});if(q.error)throw q.error;toast(`Stock updated to ${q.data}`);await loadInventory()})};
  window.PMOps.toolTransaction=tid=>{const x=cache.find(y=>y.id===tid);dialog(`Tool transaction — ${x.name}`,select('transaction_type','Action',['checkout','return','inspection','calibration'],'checkout')+field('holder_id','Holder user ID','text','',false)+field('condition','Condition','text',x.condition||'good',false)+select('shift_name','Shift',shifts,actor().shift_name)+area('notes','Notes','',false),async fd=>{const holder=value(fd,'holder_id')||null;if(holder&&!/^[0-9a-f-]{36}$/i.test(holder))throw Error('Holder user ID must be a valid UUID');const q=await sb.rpc('transact_tool',{p_tool_id:tid,p_type:value(fd,'transaction_type'),p_holder_id:holder,p_condition:value(fd,'condition')||null,p_notes:value(fd,'notes')||null,p_worker_name:actor().worker_name,p_designation:actor().designation,p_shift_name:value(fd,'shift_name')});if(q.error)throw q.error;toast(`Tool status: ${q.data}`);await loadInventory()})};
  async function inventoryHistory(){try{const [sp,tools]=await Promise.all([query(sb.from('inventory_transactions').select('*,spares(description)').order('created_at',{ascending:false}).limit(100)),query(sb.from('tool_transactions').select('*,tools(name)').eq('plant_id',S().plant.id).order('created_at',{ascending:false}).limit(100))]);dialog('Inventory transaction history',`<div class="span-2 table-wrap"><table><thead><tr><th>Date</th><th>Item</th><th>Action</th><th>Quantity / Worker</th><th>Reference</th></tr></thead><tbody>${sp.map(r=>`<tr><td>${new Date(r.created_at).toLocaleString()}</td><td>${esc(r.spares?.description)}</td><td>${esc(r.transaction_type)}</td><td>${r.quantity}</td><td>${esc(r.reference||'')}</td></tr>`).join('')}${tools.map(r=>`<tr><td>${new Date(r.created_at).toLocaleString()}</td><td>${esc(r.tools?.name)}</td><td>${esc(r.transaction_type)}</td><td>${esc(r.worker_name)}</td><td>${esc(r.notes||'')}</td></tr>`).join('')}</tbody></table></div>`,async()=>{}, {submit:'Close'});const d=$('#opsDialog');d.querySelector('form').onsubmit=e=>{e.preventDefault();d.close()}}catch(e){toast(e.message)}}

  async function loadRecovery(){toolbar('Recovery Bin','');if(!owner()){cache=[];$('#content').innerHTML='<div class="error-state"><h2>Owner access required</h2><p>Only the company owner can recover or permanently erase removed records.</p></div>';return}const tables=['assets','work_orders','file_metadata','checklist_templates','maintenance_plans','spares','tools'],groups=await Promise.all(tables.map(async table=>({table,rows:await query(sb.from(table).select('*').eq('organization_id',S().org.id).not('removed_at','is',null).order('removed_at',{ascending:false}))})));cache=groups.flatMap(g=>g.rows.map(row=>({...row,_table:g.table})));$('#content').innerHTML=`<section class="module-head"><div><h1>Recovery Bin</h1><p>Restore removed records or permanently erase them as owner</p></div></section><div class="record-grid">${cache.filter(matches).map(x=>`<article class="record-card"><div class="record-title"><div><h3>${esc(x.name||x.title||x.description||x.file_name||x.id)}</h3><p>${esc(x._table.replaceAll('_',' '))} • Removed ${x.removed_at?new Date(x.removed_at).toLocaleString():'—'}</p></div>${stateBadge('Removed')}</div><div class="actions"><button class="success" onclick="PMOps.restore('${x._table}','${x.id}')">Recover</button><button class="danger" onclick="PMOps.erase('${x._table}','${x.id}')">Permanent Erase</button></div></article>`).join('')||empty('The Recovery Bin is empty.')}</div>`}
  window.PMOps.restore=async(table,rid)=>{if(!owner())return toast('Owner access required');try{await write(sb.from(table).update({removed_at:null,removed_by:null}).eq('id',rid),'Record recovered','record_recovered',table,rid);await loadRecovery()}catch(e){toast(e.message)}};
  window.PMOps.erase=async(table,rid)=>{if(!owner())return toast('Owner access required');const confirmation=prompt('Permanent erase cannot be undone. Type ERASE to continue:');if(confirmation!=='ERASE')return;try{await audit('record_permanently_erased',table,rid);const q=await sb.from(table).delete().eq('id',rid);if(q.error)throw q.error;toast('Record permanently erased');await loadRecovery()}catch(e){toast(e.message)}};

  window.PMOps.remove=async(table,rid)=>{if(!owner())return toast('Only the owner can remove records');if(!confirm('Move this record to Recovery? It will not be permanently erased.'))return;try{await write(sb.from(table).update({removed_at:now(),removed_by:S().userId}).eq('id',rid),'Moved to Recovery','record_removed',table,rid);await render(module)}catch(e){toast(e.message)}};
  window.PMOps.exportPeople=format=>downloadData(format,`people-${tab}`,cache.filter(matches));
  function downloadData(format,filename,rows){if(!rows.length)return toast('Nothing to download');const flat=rows.map(r=>{const out={};for(const[k,v]of Object.entries(r)){if(k==='profile'&&v)for(const[pk,pv]of Object.entries(v))out[`worker_${pk}`]=Array.isArray(pv)?pv.join(', '):pv;else out[k]=typeof v==='object'&&v!==null?JSON.stringify(v):v}return out}),keys=[...new Set(flat.flatMap(r=>Object.keys(r)))],csv=[keys.join(','),...flat.map(r=>keys.map(k=>`\"${String(r[k]??'').replaceAll('\"','\"\"')}\"`).join(','))].join('\r\n'),html=`<!doctype html><html><head><meta charset=\"utf-8\"><style>body{font:12px Arial}table{border-collapse:collapse;width:100%}th,td{border:1px solid #777;padding:6px;text-align:left}th{background:#e7eef7}</style></head><body><h1>${esc(S().org.name)} — ${esc(filename.replaceAll('_',' '))}</h1><p>Generated ${new Date().toLocaleString()}</p><table><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${flat.map(r=>`<tr>${keys.map(k=>`<td>${esc(r[k]??'')}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`;if(format==='pdf'){const w=open('','_blank');if(!w)return toast('Allow pop-ups for PDF');w.document.write(html);w.document.close();setTimeout(()=>w.print(),300);return toast('Print dialog opened — choose Save as PDF')}if(format==='csv')saveDownload('\ufeff'+csv,'text/csv',filename+'.csv');if(format==='excel')saveDownload('\ufeff'+html,'application/vnd.ms-excel',filename+'.xls');if(format==='word')saveDownload(html,'application/msword',filename+'.doc');toast(`${format.toUpperCase()} downloaded`)}
  function saveDownload(data,type,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  function downloadCSV(filename,rows){if(!rows.length)return toast('Nothing to download');const keys=[...new Set(rows.flatMap(x=>Object.keys(x).filter(k=>typeof x[k]!=='object')))],csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=filename;a.click();URL.revokeObjectURL(a.href);toast('CSV downloaded')}

  return{handles:v=>['people','checklists','maintenance','inventory','recovery'].includes(v),render,enhanceVoice,audit};
}
