-- PlantMaster v4 Phase 2
create table if not exists public.shift_assignments(id uuid primary key,organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid not null references plants(id) on delete cascade,user_id uuid not null references auth.users(id),shift_name text not null,work_date date not null,status text default 'scheduled',created_by uuid references auth.users(id),created_at timestamptz default now(),unique(plant_id,user_id,work_date));
create table if not exists public.attendance(id uuid primary key,organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid not null references plants(id) on delete cascade,user_id uuid not null references auth.users(id),work_date date not null,shift_name text,status text not null,check_in timestamptz,check_out timestamptz,notes text,created_by uuid references auth.users(id),updated_at timestamptz default now(),unique(plant_id,user_id,work_date));
create table if not exists public.checklist_templates(id uuid primary key,organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid not null references plants(id) on delete cascade,asset_id uuid references assets(id) on delete cascade,name text not null,schedule text,shift_name text,instructions text,active boolean default true,created_by uuid references auth.users(id),created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.checklist_items(id uuid primary key,template_id uuid not null references checklist_templates(id) on delete cascade,sort_order int not null,label text not null,input_type text not null,unit text,required boolean default true,limits jsonb default '{}'::jsonb);
create table if not exists public.checklist_runs(id uuid primary key,organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid not null references plants(id) on delete cascade,template_id uuid not null references checklist_templates(id),asset_id uuid references assets(id),performed_by uuid not null references auth.users(id),shift_name text,status text not null,notes text,performed_at timestamptz default now());
create table if not exists public.checklist_values(id uuid primary key,run_id uuid not null references checklist_runs(id) on delete cascade,item_id uuid not null references checklist_items(id),value jsonb not null);
create table if not exists public.maintenance_plans(id uuid primary key,organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid not null references plants(id) on delete cascade,asset_id uuid references assets(id),title text not null,frequency text not null,priority text default 'medium',description text not null,assigned_to uuid references auth.users(id),next_due date,status text default 'pending',created_by uuid references auth.users(id),created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.spares(id uuid primary key,organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid not null references plants(id) on delete cascade,part_number text,description text not null,asset_id uuid references assets(id),stock numeric default 0,min_stock numeric default 0,unit text,unit_cost numeric,bin_location text,supplier text,updated_at timestamptz default now());
create table if not exists public.inventory_transactions(id uuid primary key,spare_id uuid not null references spares(id),quantity numeric not null,transaction_type text not null,reference text,performed_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.tools(id uuid primary key,organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid not null references plants(id) on delete cascade,tool_code text,name text not null,specification text,condition text,calibration_due date,status text default 'available',holder_id uuid references auth.users(id),updated_at timestamptz default now());
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid references plants(id),user_id uuid references auth.users(id),title text not null,body text,read_at timestamptz,created_at timestamptz default now());

alter table shift_assignments enable row level security;alter table attendance enable row level security;alter table checklist_templates enable row level security;alter table checklist_items enable row level security;alter table checklist_runs enable row level security;alter table checklist_values enable row level security;alter table maintenance_plans enable row level security;alter table spares enable row level security;alter table inventory_transactions enable row level security;alter table tools enable row level security;alter table notifications enable row level security;

do $$ declare t text; begin foreach t in array array['shift_assignments','attendance','checklist_templates','checklist_runs','maintenance_plans','spares','tools','notifications'] loop execute format('create policy %I on public.%I for all to authenticated using(public.is_org_member(organization_id)) with check(public.is_org_member(organization_id))',t||'_member',t);end loop;end $$;
create policy checklist_items_member on checklist_items for all to authenticated using(exists(select 1 from checklist_templates t where t.id=template_id and is_org_member(t.organization_id))) with check(exists(select 1 from checklist_templates t where t.id=template_id and is_org_member(t.organization_id)));
create policy checklist_values_member on checklist_values for all to authenticated using(exists(select 1 from checklist_runs r where r.id=run_id and is_org_member(r.organization_id))) with check(exists(select 1 from checklist_runs r where r.id=run_id and is_org_member(r.organization_id)));
create policy inventory_transactions_member on inventory_transactions for all to authenticated using(exists(select 1 from spares s where s.id=spare_id and is_org_member(s.organization_id))) with check(exists(select 1 from spares s where s.id=spare_id and is_org_member(s.organization_id)));
grant select,insert,update,delete on shift_assignments,attendance,checklist_templates,checklist_items,checklist_runs,checklist_values,maintenance_plans,spares,inventory_transactions,tools,notifications to authenticated;
