-- PlantMaster v4 Phase 3: support, manuals, problem solver and Gemini
create extension if not exists vector;
create table if not exists public.support_threads(id uuid primary key,organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid not null references plants(id) on delete cascade,asset_id uuid references assets(id),subject text not null,priority text default 'medium',status text default 'open',created_by uuid not null references auth.users(id),created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.support_messages(id uuid primary key,thread_id uuid not null references support_threads(id) on delete cascade,user_id uuid not null references auth.users(id),message text not null,created_at timestamptz default now());
create table if not exists public.technical_experiences(id uuid primary key,organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid not null references plants(id) on delete cascade,asset_id uuid references assets(id),problem text not null,symptoms text,tests text,root_cause text not null,solution text not null,tools text,parts text,downtime text,approved boolean default false,created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.manuals(id uuid primary key,organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid references plants(id),asset_id uuid references assets(id),title text not null,manufacturer text,model text,storage_path text not null,mime_type text,size_bytes bigint,status text default 'uploaded',uploaded_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.document_chunks(id bigint generated always as identity primary key,manual_id uuid not null references manuals(id) on delete cascade,page_number int,content text not null,embedding vector(768),created_at timestamptz default now());
create index if not exists document_chunks_embedding_idx on document_chunks using hnsw(embedding vector_cosine_ops);
create table if not exists public.problem_cases(id uuid primary key,organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid not null references plants(id) on delete cascade,asset_id uuid references assets(id),title text not null,symptoms text not null,alarm_code text,readings jsonb default '{}'::jsonb,mode text default 'offline',ai_answer jsonb,actual_cause text,verified_solution text,status text default 'open',created_by uuid references auth.users(id),created_at timestamptz default now(),resolved_at timestamptz);
create table if not exists public.ai_usage(id bigint generated always as identity primary key,organization_id uuid not null references organizations(id),plant_id uuid references plants(id),user_id uuid references auth.users(id),provider text,mode text,input_tokens int,output_tokens int,estimated_cost numeric,created_at timestamptz default now());

alter table support_threads enable row level security;alter table support_messages enable row level security;alter table technical_experiences enable row level security;alter table manuals enable row level security;alter table document_chunks enable row level security;alter table problem_cases enable row level security;alter table ai_usage enable row level security;
create policy support_threads_member on support_threads for all to authenticated using(is_org_member(organization_id)) with check(is_org_member(organization_id));
create policy support_messages_member on support_messages for all to authenticated using(exists(select 1 from support_threads t where t.id=thread_id and is_org_member(t.organization_id))) with check(exists(select 1 from support_threads t where t.id=thread_id and is_org_member(t.organization_id)));
create policy experiences_member on technical_experiences for all to authenticated using(is_org_member(organization_id)) with check(is_org_member(organization_id));
create policy manuals_member on manuals for all to authenticated using(is_org_member(organization_id)) with check(is_org_member(organization_id));
create policy chunks_member on document_chunks for select to authenticated using(exists(select 1 from manuals m where m.id=manual_id and is_org_member(m.organization_id)));
create policy cases_member on problem_cases for all to authenticated using(is_org_member(organization_id)) with check(is_org_member(organization_id));
create policy ai_usage_member on ai_usage for select to authenticated using(is_org_member(organization_id));
grant select,insert,update,delete on support_threads,support_messages,technical_experiences,manuals,problem_cases to authenticated;grant select on document_chunks,ai_usage to authenticated;grant usage,select on all sequences in schema public to authenticated;
