-- PlantMaster v4 Phase 4: branding, invitations, status history and daily reports
create table if not exists public.organization_settings(organization_id uuid primary key references organizations(id) on delete cascade,app_name text default 'PlantMaster Pro',plant_display_name text,logo_path text,primary_color text default '#3b82f6',secondary_color text default '#06b6d4',theme text default 'industrial',pattern text default 'grid',address text,contact text,email text,report_time time default '11:00',footer_text text,updated_at timestamptz default now());
create table if not exists public.invitations(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid references plants(id) on delete cascade,email text,role text not null,token uuid not null default gen_random_uuid(),expires_at timestamptz not null default(now()+interval '7 days'),accepted_at timestamptz,created_by uuid references auth.users(id),created_at timestamptz default now());
create table if not exists public.asset_status_history(id bigint generated always as identity primary key,organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid not null references plants(id) on delete cascade,asset_id uuid not null references assets(id) on delete cascade,old_state text,new_state text not null,changed_by uuid references auth.users(id),changed_at timestamptz default now());
create table if not exists public.report_dispatches(id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id) on delete cascade,plant_id uuid references plants(id),report_date date not null,recipient text not null,summary text,status text default 'pending',approved_by uuid references auth.users(id),sent_at timestamptz,created_at timestamptz default now());
alter table organization_settings enable row level security;alter table invitations enable row level security;alter table asset_status_history enable row level security;alter table report_dispatches enable row level security;
create policy settings_read on organization_settings for select to authenticated using(is_org_member(organization_id));create policy settings_write on organization_settings for all to authenticated using(is_org_member(organization_id) and org_role(organization_id) in('owner','manager')) with check(is_org_member(organization_id) and org_role(organization_id) in('owner','manager'));
create policy invites_manage on invitations for all to authenticated using(is_org_member(organization_id) and org_role(organization_id) in('owner','manager')) with check(is_org_member(organization_id) and org_role(organization_id) in('owner','manager'));
create policy status_read on asset_status_history for select to authenticated using(is_org_member(organization_id));create policy status_insert on asset_status_history for insert to authenticated with check(is_org_member(organization_id));
create policy reports_member on report_dispatches for all to authenticated using(is_org_member(organization_id)) with check(is_org_member(organization_id));
grant select,insert,update,delete on organization_settings,invitations,asset_status_history,report_dispatches to authenticated;grant usage,select on all sequences in schema public to authenticated;
alter table public.organization_settings add column if not exists pattern text default 'grid';
